// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: task/v1/task.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BaseResponse, PaginatedResponse } from "../../base/base";
import { Struct } from "../../google/protobuf/struct";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "task.v1";

export enum TaskType {
  /** TASK_TYPE_UNSPECIFIED - Default */
  TASK_TYPE_UNSPECIFIED = 0,
  TASK_TYPE_ACCOUNT_MIGRATION = 1,
  TASK_TYPE_EXPORT_DATA = 2,
  TASK_TYPE_IMPORT_DATA = 3,
  UNRECOGNIZED = -1,
}

export function taskTypeFromJSON(object: any): TaskType {
  switch (object) {
    case 0:
    case "TASK_TYPE_UNSPECIFIED":
      return TaskType.TASK_TYPE_UNSPECIFIED;
    case 1:
    case "TASK_TYPE_ACCOUNT_MIGRATION":
      return TaskType.TASK_TYPE_ACCOUNT_MIGRATION;
    case 2:
    case "TASK_TYPE_EXPORT_DATA":
      return TaskType.TASK_TYPE_EXPORT_DATA;
    case 3:
    case "TASK_TYPE_IMPORT_DATA":
      return TaskType.TASK_TYPE_IMPORT_DATA;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TaskType.UNRECOGNIZED;
  }
}

export function taskTypeToJSON(object: TaskType): string {
  switch (object) {
    case TaskType.TASK_TYPE_UNSPECIFIED:
      return "TASK_TYPE_UNSPECIFIED";
    case TaskType.TASK_TYPE_ACCOUNT_MIGRATION:
      return "TASK_TYPE_ACCOUNT_MIGRATION";
    case TaskType.TASK_TYPE_EXPORT_DATA:
      return "TASK_TYPE_EXPORT_DATA";
    case TaskType.TASK_TYPE_IMPORT_DATA:
      return "TASK_TYPE_IMPORT_DATA";
    case TaskType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TaskStatus {
  /** TASK_STATUS_UNSPECIFIED - Default */
  TASK_STATUS_UNSPECIFIED = 0,
  TASK_STATUS_PENDING = 1,
  TASK_STATUS_RUNNING = 2,
  TASK_STATUS_COMPLETED = 3,
  TASK_STATUS_FAILED = 4,
  TASK_STATUS_CANCELLED = 5,
  UNRECOGNIZED = -1,
}

export function taskStatusFromJSON(object: any): TaskStatus {
  switch (object) {
    case 0:
    case "TASK_STATUS_UNSPECIFIED":
      return TaskStatus.TASK_STATUS_UNSPECIFIED;
    case 1:
    case "TASK_STATUS_PENDING":
      return TaskStatus.TASK_STATUS_PENDING;
    case 2:
    case "TASK_STATUS_RUNNING":
      return TaskStatus.TASK_STATUS_RUNNING;
    case 3:
    case "TASK_STATUS_COMPLETED":
      return TaskStatus.TASK_STATUS_COMPLETED;
    case 4:
    case "TASK_STATUS_FAILED":
      return TaskStatus.TASK_STATUS_FAILED;
    case 5:
    case "TASK_STATUS_CANCELLED":
      return TaskStatus.TASK_STATUS_CANCELLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TaskStatus.UNRECOGNIZED;
  }
}

export function taskStatusToJSON(object: TaskStatus): string {
  switch (object) {
    case TaskStatus.TASK_STATUS_UNSPECIFIED:
      return "TASK_STATUS_UNSPECIFIED";
    case TaskStatus.TASK_STATUS_PENDING:
      return "TASK_STATUS_PENDING";
    case TaskStatus.TASK_STATUS_RUNNING:
      return "TASK_STATUS_RUNNING";
    case TaskStatus.TASK_STATUS_COMPLETED:
      return "TASK_STATUS_COMPLETED";
    case TaskStatus.TASK_STATUS_FAILED:
      return "TASK_STATUS_FAILED";
    case TaskStatus.TASK_STATUS_CANCELLED:
      return "TASK_STATUS_CANCELLED";
    case TaskStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Task {
  id: string;
  type: TaskType;
  status: TaskStatus;
  payload: { [key: string]: any } | undefined;
  result: { [key: string]: any } | undefined;
  progress: number;
  totalItems: number;
  processedItems: number;
  startedAt: Date | undefined;
  completedAt: Date | undefined;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface TaskQuery {
  page: number;
  limit: number;
  status: TaskStatus;
  type: TaskType;
}

export interface ListTasksReq {
  query: TaskQuery | undefined;
}

export interface ListTasksRes {
  data: Task[];
  pagination: PaginatedResponse | undefined;
  base: BaseResponse | undefined;
}

export interface GetTaskReq {
  id: string;
}

export interface GetTaskRes {
  task: Task | undefined;
  base: BaseResponse | undefined;
}

export interface CancelTaskReq {
  id: string;
}

export interface CancelTaskRes {
  base: BaseResponse | undefined;
}

export interface RetryTaskReq {
  id: string;
}

export interface RetryTaskRes {
  task: Task | undefined;
  base: BaseResponse | undefined;
}

function createBaseTask(): Task {
  return {
    id: "",
    type: 0,
    status: 0,
    payload: undefined,
    result: undefined,
    progress: 0,
    totalItems: 0,
    processedItems: 0,
    startedAt: undefined,
    completedAt: undefined,
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const Task: MessageFns<Task> = {
  encode(message: Task, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.status !== 0) {
      writer.uint32(24).int32(message.status);
    }
    if (message.payload !== undefined) {
      Struct.encode(Struct.wrap(message.payload), writer.uint32(34).fork()).join();
    }
    if (message.result !== undefined) {
      Struct.encode(Struct.wrap(message.result), writer.uint32(42).fork()).join();
    }
    if (message.progress !== 0) {
      writer.uint32(48).int32(message.progress);
    }
    if (message.totalItems !== 0) {
      writer.uint32(56).int32(message.totalItems);
    }
    if (message.processedItems !== 0) {
      writer.uint32(64).int32(message.processedItems);
    }
    if (message.startedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.startedAt), writer.uint32(74).fork()).join();
    }
    if (message.completedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.completedAt), writer.uint32(82).fork()).join();
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(90).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Task {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTask();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payload = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.result = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.progress = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalItems = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.processedItems = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.startedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.completedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Task {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      type: isSet(object.type) ? taskTypeFromJSON(object.type) : 0,
      status: isSet(object.status) ? taskStatusFromJSON(object.status) : 0,
      payload: isObject(object.payload) ? object.payload : undefined,
      result: isObject(object.result) ? object.result : undefined,
      progress: isSet(object.progress) ? globalThis.Number(object.progress) : 0,
      totalItems: isSet(object.totalItems) ? globalThis.Number(object.totalItems) : 0,
      processedItems: isSet(object.processedItems) ? globalThis.Number(object.processedItems) : 0,
      startedAt: isSet(object.startedAt) ? fromJsonTimestamp(object.startedAt) : undefined,
      completedAt: isSet(object.completedAt) ? fromJsonTimestamp(object.completedAt) : undefined,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: Task): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.type !== 0) {
      obj.type = taskTypeToJSON(message.type);
    }
    if (message.status !== 0) {
      obj.status = taskStatusToJSON(message.status);
    }
    if (message.payload !== undefined) {
      obj.payload = message.payload;
    }
    if (message.result !== undefined) {
      obj.result = message.result;
    }
    if (message.progress !== 0) {
      obj.progress = Math.round(message.progress);
    }
    if (message.totalItems !== 0) {
      obj.totalItems = Math.round(message.totalItems);
    }
    if (message.processedItems !== 0) {
      obj.processedItems = Math.round(message.processedItems);
    }
    if (message.startedAt !== undefined) {
      obj.startedAt = message.startedAt.toISOString();
    }
    if (message.completedAt !== undefined) {
      obj.completedAt = message.completedAt.toISOString();
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Task>, I>>(base?: I): Task {
    return Task.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Task>, I>>(object: I): Task {
    const message = createBaseTask();
    message.id = object.id ?? "";
    message.type = object.type ?? 0;
    message.status = object.status ?? 0;
    message.payload = object.payload ?? undefined;
    message.result = object.result ?? undefined;
    message.progress = object.progress ?? 0;
    message.totalItems = object.totalItems ?? 0;
    message.processedItems = object.processedItems ?? 0;
    message.startedAt = object.startedAt ?? undefined;
    message.completedAt = object.completedAt ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseTaskQuery(): TaskQuery {
  return { page: 0, limit: 0, status: 0, type: 0 };
}

export const TaskQuery: MessageFns<TaskQuery> = {
  encode(message: TaskQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.status !== 0) {
      writer.uint32(24).int32(message.status);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskQuery {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      status: isSet(object.status) ? taskStatusFromJSON(object.status) : 0,
      type: isSet(object.type) ? taskTypeFromJSON(object.type) : 0,
    };
  },

  toJSON(message: TaskQuery): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.status !== 0) {
      obj.status = taskStatusToJSON(message.status);
    }
    if (message.type !== 0) {
      obj.type = taskTypeToJSON(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskQuery>, I>>(base?: I): TaskQuery {
    return TaskQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskQuery>, I>>(object: I): TaskQuery {
    const message = createBaseTaskQuery();
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.status = object.status ?? 0;
    message.type = object.type ?? 0;
    return message;
  },
};

function createBaseListTasksReq(): ListTasksReq {
  return { query: undefined };
}

export const ListTasksReq: MessageFns<ListTasksReq> = {
  encode(message: ListTasksReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== undefined) {
      TaskQuery.encode(message.query, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTasksReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTasksReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = TaskQuery.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTasksReq {
    return { query: isSet(object.query) ? TaskQuery.fromJSON(object.query) : undefined };
  },

  toJSON(message: ListTasksReq): unknown {
    const obj: any = {};
    if (message.query !== undefined) {
      obj.query = TaskQuery.toJSON(message.query);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTasksReq>, I>>(base?: I): ListTasksReq {
    return ListTasksReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTasksReq>, I>>(object: I): ListTasksReq {
    const message = createBaseListTasksReq();
    message.query = (object.query !== undefined && object.query !== null)
      ? TaskQuery.fromPartial(object.query)
      : undefined;
    return message;
  },
};

function createBaseListTasksRes(): ListTasksRes {
  return { data: [], pagination: undefined, base: undefined };
}

export const ListTasksRes: MessageFns<ListTasksRes> = {
  encode(message: ListTasksRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      Task.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PaginatedResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTasksRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTasksRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(Task.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PaginatedResponse.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTasksRes {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => Task.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PaginatedResponse.fromJSON(object.pagination) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: ListTasksRes): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => Task.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PaginatedResponse.toJSON(message.pagination);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTasksRes>, I>>(base?: I): ListTasksRes {
    return ListTasksRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTasksRes>, I>>(object: I): ListTasksRes {
    const message = createBaseListTasksRes();
    message.data = object.data?.map((e) => Task.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginatedResponse.fromPartial(object.pagination)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetTaskReq(): GetTaskReq {
  return { id: "" };
}

export const GetTaskReq: MessageFns<GetTaskReq> = {
  encode(message: GetTaskReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTaskReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTaskReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTaskReq {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetTaskReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTaskReq>, I>>(base?: I): GetTaskReq {
    return GetTaskReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTaskReq>, I>>(object: I): GetTaskReq {
    const message = createBaseGetTaskReq();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetTaskRes(): GetTaskRes {
  return { task: undefined, base: undefined };
}

export const GetTaskRes: MessageFns<GetTaskRes> = {
  encode(message: GetTaskRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.task !== undefined) {
      Task.encode(message.task, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTaskRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTaskRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.task = Task.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTaskRes {
    return {
      task: isSet(object.task) ? Task.fromJSON(object.task) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetTaskRes): unknown {
    const obj: any = {};
    if (message.task !== undefined) {
      obj.task = Task.toJSON(message.task);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTaskRes>, I>>(base?: I): GetTaskRes {
    return GetTaskRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTaskRes>, I>>(object: I): GetTaskRes {
    const message = createBaseGetTaskRes();
    message.task = (object.task !== undefined && object.task !== null) ? Task.fromPartial(object.task) : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseCancelTaskReq(): CancelTaskReq {
  return { id: "" };
}

export const CancelTaskReq: MessageFns<CancelTaskReq> = {
  encode(message: CancelTaskReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelTaskReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelTaskReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelTaskReq {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: CancelTaskReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelTaskReq>, I>>(base?: I): CancelTaskReq {
    return CancelTaskReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelTaskReq>, I>>(object: I): CancelTaskReq {
    const message = createBaseCancelTaskReq();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseCancelTaskRes(): CancelTaskRes {
  return { base: undefined };
}

export const CancelTaskRes: MessageFns<CancelTaskRes> = {
  encode(message: CancelTaskRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelTaskRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelTaskRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelTaskRes {
    return { base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined };
  },

  toJSON(message: CancelTaskRes): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelTaskRes>, I>>(base?: I): CancelTaskRes {
    return CancelTaskRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelTaskRes>, I>>(object: I): CancelTaskRes {
    const message = createBaseCancelTaskRes();
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseRetryTaskReq(): RetryTaskReq {
  return { id: "" };
}

export const RetryTaskReq: MessageFns<RetryTaskReq> = {
  encode(message: RetryTaskReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RetryTaskReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRetryTaskReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RetryTaskReq {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: RetryTaskReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RetryTaskReq>, I>>(base?: I): RetryTaskReq {
    return RetryTaskReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetryTaskReq>, I>>(object: I): RetryTaskReq {
    const message = createBaseRetryTaskReq();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseRetryTaskRes(): RetryTaskRes {
  return { task: undefined, base: undefined };
}

export const RetryTaskRes: MessageFns<RetryTaskRes> = {
  encode(message: RetryTaskRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.task !== undefined) {
      Task.encode(message.task, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RetryTaskRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRetryTaskRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.task = Task.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RetryTaskRes {
    return {
      task: isSet(object.task) ? Task.fromJSON(object.task) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: RetryTaskRes): unknown {
    const obj: any = {};
    if (message.task !== undefined) {
      obj.task = Task.toJSON(message.task);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RetryTaskRes>, I>>(base?: I): RetryTaskRes {
    return RetryTaskRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetryTaskRes>, I>>(object: I): RetryTaskRes {
    const message = createBaseRetryTaskRes();
    message.task = (object.task !== undefined && object.task !== null) ? Task.fromPartial(object.task) : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

export interface TaskService {
  /** List all tasks */
  ListTasks(request: ListTasksReq): Promise<ListTasksRes>;
  /** Get task details */
  GetTask(request: GetTaskReq): Promise<GetTaskRes>;
  /** Cancel a task */
  CancelTask(request: CancelTaskReq): Promise<CancelTaskRes>;
  /** Retry a task */
  RetryTask(request: RetryTaskReq): Promise<RetryTaskRes>;
}

export const TaskServiceServiceName = "task.v1.TaskService";
export class TaskServiceClientImpl implements TaskService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TaskServiceServiceName;
    this.rpc = rpc;
    this.ListTasks = this.ListTasks.bind(this);
    this.GetTask = this.GetTask.bind(this);
    this.CancelTask = this.CancelTask.bind(this);
    this.RetryTask = this.RetryTask.bind(this);
  }
  ListTasks(request: ListTasksReq): Promise<ListTasksRes> {
    const data = ListTasksReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListTasks", data);
    return promise.then((data) => ListTasksRes.decode(new BinaryReader(data)));
  }

  GetTask(request: GetTaskReq): Promise<GetTaskRes> {
    const data = GetTaskReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTask", data);
    return promise.then((data) => GetTaskRes.decode(new BinaryReader(data)));
  }

  CancelTask(request: CancelTaskReq): Promise<CancelTaskRes> {
    const data = CancelTaskReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "CancelTask", data);
    return promise.then((data) => CancelTaskRes.decode(new BinaryReader(data)));
  }

  RetryTask(request: RetryTaskReq): Promise<RetryTaskRes> {
    const data = RetryTaskReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "RetryTask", data);
    return promise.then((data) => RetryTaskRes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
