// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: base/base.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "base";

/**
 * Share enum
 * Account Type
 */
export enum AccountType {
  /** ACCOUNT_TYPE_UNSPECIFIED - Default */
  ACCOUNT_TYPE_UNSPECIFIED = 0,
  ACCOUNT_TYPE_ASSET = 1,
  ACCOUNT_TYPE_LIABILITY = 2,
  ACCOUNT_TYPE_INCOME = 3,
  ACCOUNT_TYPE_EXPENSE = 4,
  ACCOUNT_TYPE_EQUITY = 5,
  UNRECOGNIZED = -1,
}

export function accountTypeFromJSON(object: any): AccountType {
  switch (object) {
    case 0:
    case "ACCOUNT_TYPE_UNSPECIFIED":
      return AccountType.ACCOUNT_TYPE_UNSPECIFIED;
    case 1:
    case "ACCOUNT_TYPE_ASSET":
      return AccountType.ACCOUNT_TYPE_ASSET;
    case 2:
    case "ACCOUNT_TYPE_LIABILITY":
      return AccountType.ACCOUNT_TYPE_LIABILITY;
    case 3:
    case "ACCOUNT_TYPE_INCOME":
      return AccountType.ACCOUNT_TYPE_INCOME;
    case 4:
    case "ACCOUNT_TYPE_EXPENSE":
      return AccountType.ACCOUNT_TYPE_EXPENSE;
    case 5:
    case "ACCOUNT_TYPE_EQUITY":
      return AccountType.ACCOUNT_TYPE_EQUITY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AccountType.UNRECOGNIZED;
  }
}

export function accountTypeToJSON(object: AccountType): string {
  switch (object) {
    case AccountType.ACCOUNT_TYPE_UNSPECIFIED:
      return "ACCOUNT_TYPE_UNSPECIFIED";
    case AccountType.ACCOUNT_TYPE_ASSET:
      return "ACCOUNT_TYPE_ASSET";
    case AccountType.ACCOUNT_TYPE_LIABILITY:
      return "ACCOUNT_TYPE_LIABILITY";
    case AccountType.ACCOUNT_TYPE_INCOME:
      return "ACCOUNT_TYPE_INCOME";
    case AccountType.ACCOUNT_TYPE_EXPENSE:
      return "ACCOUNT_TYPE_EXPENSE";
    case AccountType.ACCOUNT_TYPE_EQUITY:
      return "ACCOUNT_TYPE_EQUITY";
    case AccountType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Transaction Type */
export enum TransactionType {
  /** TRANSACTION_TYPE_UNSPECIFIED - Default */
  TRANSACTION_TYPE_UNSPECIFIED = 0,
  TRANSACTION_TYPE_INCOME = 1,
  TRANSACTION_TYPE_EXPENSE = 2,
  TRANSACTION_TYPE_TRANSFER = 3,
  TRANSACTION_TYPE_OPENING_BALANCE = 4,
  UNRECOGNIZED = -1,
}

export function transactionTypeFromJSON(object: any): TransactionType {
  switch (object) {
    case 0:
    case "TRANSACTION_TYPE_UNSPECIFIED":
      return TransactionType.TRANSACTION_TYPE_UNSPECIFIED;
    case 1:
    case "TRANSACTION_TYPE_INCOME":
      return TransactionType.TRANSACTION_TYPE_INCOME;
    case 2:
    case "TRANSACTION_TYPE_EXPENSE":
      return TransactionType.TRANSACTION_TYPE_EXPENSE;
    case 3:
    case "TRANSACTION_TYPE_TRANSFER":
      return TransactionType.TRANSACTION_TYPE_TRANSFER;
    case 4:
    case "TRANSACTION_TYPE_OPENING_BALANCE":
      return TransactionType.TRANSACTION_TYPE_OPENING_BALANCE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransactionType.UNRECOGNIZED;
  }
}

export function transactionTypeToJSON(object: TransactionType): string {
  switch (object) {
    case TransactionType.TRANSACTION_TYPE_UNSPECIFIED:
      return "TRANSACTION_TYPE_UNSPECIFIED";
    case TransactionType.TRANSACTION_TYPE_INCOME:
      return "TRANSACTION_TYPE_INCOME";
    case TransactionType.TRANSACTION_TYPE_EXPENSE:
      return "TRANSACTION_TYPE_EXPENSE";
    case TransactionType.TRANSACTION_TYPE_TRANSFER:
      return "TRANSACTION_TYPE_TRANSFER";
    case TransactionType.TRANSACTION_TYPE_OPENING_BALANCE:
      return "TRANSACTION_TYPE_OPENING_BALANCE";
    case TransactionType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** User Level Type */
export enum UserLevelType {
  /** USER_LEVEL_TYPE_UNSPECIFIED - Default */
  USER_LEVEL_TYPE_UNSPECIFIED = 0,
  USER_LEVEL_TYPE_FREE = 1,
  USER_LEVEL_TYPE_PRO = 2,
  UNRECOGNIZED = -1,
}

export function userLevelTypeFromJSON(object: any): UserLevelType {
  switch (object) {
    case 0:
    case "USER_LEVEL_TYPE_UNSPECIFIED":
      return UserLevelType.USER_LEVEL_TYPE_UNSPECIFIED;
    case 1:
    case "USER_LEVEL_TYPE_FREE":
      return UserLevelType.USER_LEVEL_TYPE_FREE;
    case 2:
    case "USER_LEVEL_TYPE_PRO":
      return UserLevelType.USER_LEVEL_TYPE_PRO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserLevelType.UNRECOGNIZED;
  }
}

export function userLevelTypeToJSON(object: UserLevelType): string {
  switch (object) {
    case UserLevelType.USER_LEVEL_TYPE_UNSPECIFIED:
      return "USER_LEVEL_TYPE_UNSPECIFIED";
    case UserLevelType.USER_LEVEL_TYPE_FREE:
      return "USER_LEVEL_TYPE_FREE";
    case UserLevelType.USER_LEVEL_TYPE_PRO:
      return "USER_LEVEL_TYPE_PRO";
    case UserLevelType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Base response included in most API responses */
export interface BaseResponse {
  message: string;
}

/** Pagination metadata */
export interface PaginatedResponse {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/** User theme preference */
export interface Theme {
  id: string;
  name: string;
  isDark: boolean;
  colors: ThemeColors | undefined;
}

/** Specific colors for the theme */
export interface ThemeColors {
  primary: string;
  bg: string;
  card: string;
  text: string;
  muted: string;
  border: string;
}

/** UI configuration for account types */
export interface AccountTypeConfig {
  label: string;
  color: string;
  bg: string;
  icon: string;
}

/** Share messages */
export interface Money {
  /**
   * ISO 4217 Currency Code, such as "CNY", "USD", "JPY"
   * If it's a stock or custom asset, use "AAPL", "BTC"
   */
  currencyCode: string;
  /** Integer part. For example, 100.50 yuan, store 100 */
  units: string;
  /**
   * Decimal part, in nanos (10^-9). For example, 0.50 yuan, store 500,000,000
   * Range must be between -999,999,999 and +999,999,999
   */
  nanos: number;
}

function createBaseBaseResponse(): BaseResponse {
  return { message: "" };
}

export const BaseResponse: MessageFns<BaseResponse> = {
  encode(message: BaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BaseResponse {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: BaseResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BaseResponse>, I>>(base?: I): BaseResponse {
    return BaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BaseResponse>, I>>(object: I): BaseResponse {
    const message = createBaseBaseResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBasePaginatedResponse(): PaginatedResponse {
  return { total: 0, page: 0, limit: 0, totalPages: 0 };
}

export const PaginatedResponse: MessageFns<PaginatedResponse> = {
  encode(message: PaginatedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total !== 0) {
      writer.uint32(8).int32(message.total);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.totalPages !== 0) {
      writer.uint32(32).int32(message.totalPages);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaginatedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginatedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalPages = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaginatedResponse {
    return {
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      totalPages: isSet(object.totalPages) ? globalThis.Number(object.totalPages) : 0,
    };
  },

  toJSON(message: PaginatedResponse): unknown {
    const obj: any = {};
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.totalPages !== 0) {
      obj.totalPages = Math.round(message.totalPages);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaginatedResponse>, I>>(base?: I): PaginatedResponse {
    return PaginatedResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaginatedResponse>, I>>(object: I): PaginatedResponse {
    const message = createBasePaginatedResponse();
    message.total = object.total ?? 0;
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.totalPages = object.totalPages ?? 0;
    return message;
  },
};

function createBaseTheme(): Theme {
  return { id: "", name: "", isDark: false, colors: undefined };
}

export const Theme: MessageFns<Theme> = {
  encode(message: Theme, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.isDark !== false) {
      writer.uint32(24).bool(message.isDark);
    }
    if (message.colors !== undefined) {
      ThemeColors.encode(message.colors, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Theme {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTheme();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isDark = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.colors = ThemeColors.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Theme {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      isDark: isSet(object.isDark) ? globalThis.Boolean(object.isDark) : false,
      colors: isSet(object.colors) ? ThemeColors.fromJSON(object.colors) : undefined,
    };
  },

  toJSON(message: Theme): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.isDark !== false) {
      obj.isDark = message.isDark;
    }
    if (message.colors !== undefined) {
      obj.colors = ThemeColors.toJSON(message.colors);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Theme>, I>>(base?: I): Theme {
    return Theme.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Theme>, I>>(object: I): Theme {
    const message = createBaseTheme();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.isDark = object.isDark ?? false;
    message.colors = (object.colors !== undefined && object.colors !== null)
      ? ThemeColors.fromPartial(object.colors)
      : undefined;
    return message;
  },
};

function createBaseThemeColors(): ThemeColors {
  return { primary: "", bg: "", card: "", text: "", muted: "", border: "" };
}

export const ThemeColors: MessageFns<ThemeColors> = {
  encode(message: ThemeColors, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.primary !== "") {
      writer.uint32(10).string(message.primary);
    }
    if (message.bg !== "") {
      writer.uint32(18).string(message.bg);
    }
    if (message.card !== "") {
      writer.uint32(26).string(message.card);
    }
    if (message.text !== "") {
      writer.uint32(34).string(message.text);
    }
    if (message.muted !== "") {
      writer.uint32(42).string(message.muted);
    }
    if (message.border !== "") {
      writer.uint32(50).string(message.border);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ThemeColors {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseThemeColors();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.primary = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bg = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.card = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.muted = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.border = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ThemeColors {
    return {
      primary: isSet(object.primary) ? globalThis.String(object.primary) : "",
      bg: isSet(object.bg) ? globalThis.String(object.bg) : "",
      card: isSet(object.card) ? globalThis.String(object.card) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      muted: isSet(object.muted) ? globalThis.String(object.muted) : "",
      border: isSet(object.border) ? globalThis.String(object.border) : "",
    };
  },

  toJSON(message: ThemeColors): unknown {
    const obj: any = {};
    if (message.primary !== "") {
      obj.primary = message.primary;
    }
    if (message.bg !== "") {
      obj.bg = message.bg;
    }
    if (message.card !== "") {
      obj.card = message.card;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.muted !== "") {
      obj.muted = message.muted;
    }
    if (message.border !== "") {
      obj.border = message.border;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ThemeColors>, I>>(base?: I): ThemeColors {
    return ThemeColors.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ThemeColors>, I>>(object: I): ThemeColors {
    const message = createBaseThemeColors();
    message.primary = object.primary ?? "";
    message.bg = object.bg ?? "";
    message.card = object.card ?? "";
    message.text = object.text ?? "";
    message.muted = object.muted ?? "";
    message.border = object.border ?? "";
    return message;
  },
};

function createBaseAccountTypeConfig(): AccountTypeConfig {
  return { label: "", color: "", bg: "", icon: "" };
}

export const AccountTypeConfig: MessageFns<AccountTypeConfig> = {
  encode(message: AccountTypeConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.label !== "") {
      writer.uint32(10).string(message.label);
    }
    if (message.color !== "") {
      writer.uint32(18).string(message.color);
    }
    if (message.bg !== "") {
      writer.uint32(26).string(message.bg);
    }
    if (message.icon !== "") {
      writer.uint32(34).string(message.icon);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountTypeConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountTypeConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.color = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bg = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountTypeConfig {
    return {
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      color: isSet(object.color) ? globalThis.String(object.color) : "",
      bg: isSet(object.bg) ? globalThis.String(object.bg) : "",
      icon: isSet(object.icon) ? globalThis.String(object.icon) : "",
    };
  },

  toJSON(message: AccountTypeConfig): unknown {
    const obj: any = {};
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.color !== "") {
      obj.color = message.color;
    }
    if (message.bg !== "") {
      obj.bg = message.bg;
    }
    if (message.icon !== "") {
      obj.icon = message.icon;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountTypeConfig>, I>>(base?: I): AccountTypeConfig {
    return AccountTypeConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountTypeConfig>, I>>(object: I): AccountTypeConfig {
    const message = createBaseAccountTypeConfig();
    message.label = object.label ?? "";
    message.color = object.color ?? "";
    message.bg = object.bg ?? "";
    message.icon = object.icon ?? "";
    return message;
  },
};

function createBaseMoney(): Money {
  return { currencyCode: "", units: "0", nanos: 0 };
}

export const Money: MessageFns<Money> = {
  encode(message: Money, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currencyCode !== "") {
      writer.uint32(10).string(message.currencyCode);
    }
    if (message.units !== "0") {
      writer.uint32(16).int64(message.units);
    }
    if (message.nanos !== 0) {
      writer.uint32(24).int32(message.nanos);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Money {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoney();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.currencyCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.units = reader.int64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.nanos = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Money {
    return {
      currencyCode: isSet(object.currencyCode) ? globalThis.String(object.currencyCode) : "",
      units: isSet(object.units) ? globalThis.String(object.units) : "0",
      nanos: isSet(object.nanos) ? globalThis.Number(object.nanos) : 0,
    };
  },

  toJSON(message: Money): unknown {
    const obj: any = {};
    if (message.currencyCode !== "") {
      obj.currencyCode = message.currencyCode;
    }
    if (message.units !== "0") {
      obj.units = message.units;
    }
    if (message.nanos !== 0) {
      obj.nanos = Math.round(message.nanos);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Money>, I>>(base?: I): Money {
    return Money.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Money>, I>>(object: I): Money {
    const message = createBaseMoney();
    message.currencyCode = object.currencyCode ?? "";
    message.units = object.units ?? "0";
    message.nanos = object.nanos ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
