// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.4
// source: config/v1/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AccountTypeConfig, BaseResponse, Theme } from "../../base/base";

export const protobufPackage = "config.v1";

export interface ListCurrenciesReq {
}

export interface ListCurrenciesRes {
  codes: string[];
  currencies: string[];
  base: BaseResponse | undefined;
}

export interface AddCurrencyReq {
  code: string;
}

export interface AddCurrencyRes {
  codes: string[];
  currencies: string[];
  base: BaseResponse | undefined;
}

export interface DeleteCurrencyReq {
  code: string;
}

export interface DeleteCurrencyRes {
  base: BaseResponse | undefined;
}

export interface GetThemesReq {
}

export interface GetThemesRes {
  themes: Theme[];
  base: BaseResponse | undefined;
}

export interface GetAccountTypesReq {
}

export interface GetAccountTypesRes {
  types: { [key: number]: AccountTypeConfig };
  base: BaseResponse | undefined;
}

export interface GetAccountTypesRes_TypesEntry {
  key: number;
  value: AccountTypeConfig | undefined;
}

/**
 * ExchangeRate is a single anchor-relative exchange rate. The rate is serialized
 * as a decimal string to preserve precision (never a float).
 */
export interface ExchangeRate {
  currency: string;
  rate: string;
  source: string;
  updatedAt: string;
}

export interface GetExchangeRatesReq {
}

export interface GetExchangeRatesRes {
  anchor: string;
  rates: ExchangeRate[];
  base: BaseResponse | undefined;
}

export interface SetExchangeRateReq {
  currency: string;
  rate: string;
}

export interface SetExchangeRateRes {
  rate: ExchangeRate | undefined;
  base: BaseResponse | undefined;
}

function createBaseListCurrenciesReq(): ListCurrenciesReq {
  return {};
}

export const ListCurrenciesReq: MessageFns<ListCurrenciesReq> = {
  encode(_: ListCurrenciesReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCurrenciesReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCurrenciesReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListCurrenciesReq {
    return {};
  },

  toJSON(_: ListCurrenciesReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCurrenciesReq>, I>>(base?: I): ListCurrenciesReq {
    return ListCurrenciesReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCurrenciesReq>, I>>(_: I): ListCurrenciesReq {
    const message = createBaseListCurrenciesReq();
    return message;
  },
};

function createBaseListCurrenciesRes(): ListCurrenciesRes {
  return { codes: [], currencies: [], base: undefined };
}

export const ListCurrenciesRes: MessageFns<ListCurrenciesRes> = {
  encode(message: ListCurrenciesRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.codes) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.currencies) {
      writer.uint32(18).string(v!);
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCurrenciesRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCurrenciesRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.codes.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currencies.push(reader.string());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListCurrenciesRes {
    return {
      codes: globalThis.Array.isArray(object?.codes) ? object.codes.map((e: any) => globalThis.String(e)) : [],
      currencies: globalThis.Array.isArray(object?.currencies)
        ? object.currencies.map((e: any) => globalThis.String(e))
        : [],
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: ListCurrenciesRes): unknown {
    const obj: any = {};
    if (message.codes?.length) {
      obj.codes = message.codes;
    }
    if (message.currencies?.length) {
      obj.currencies = message.currencies;
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCurrenciesRes>, I>>(base?: I): ListCurrenciesRes {
    return ListCurrenciesRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCurrenciesRes>, I>>(object: I): ListCurrenciesRes {
    const message = createBaseListCurrenciesRes();
    message.codes = object.codes?.map((e) => e) || [];
    message.currencies = object.currencies?.map((e) => e) || [];
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseAddCurrencyReq(): AddCurrencyReq {
  return { code: "" };
}

export const AddCurrencyReq: MessageFns<AddCurrencyReq> = {
  encode(message: AddCurrencyReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddCurrencyReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddCurrencyReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddCurrencyReq {
    return { code: isSet(object.code) ? globalThis.String(object.code) : "" };
  },

  toJSON(message: AddCurrencyReq): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddCurrencyReq>, I>>(base?: I): AddCurrencyReq {
    return AddCurrencyReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddCurrencyReq>, I>>(object: I): AddCurrencyReq {
    const message = createBaseAddCurrencyReq();
    message.code = object.code ?? "";
    return message;
  },
};

function createBaseAddCurrencyRes(): AddCurrencyRes {
  return { codes: [], currencies: [], base: undefined };
}

export const AddCurrencyRes: MessageFns<AddCurrencyRes> = {
  encode(message: AddCurrencyRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.codes) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.currencies) {
      writer.uint32(18).string(v!);
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddCurrencyRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddCurrencyRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.codes.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currencies.push(reader.string());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddCurrencyRes {
    return {
      codes: globalThis.Array.isArray(object?.codes) ? object.codes.map((e: any) => globalThis.String(e)) : [],
      currencies: globalThis.Array.isArray(object?.currencies)
        ? object.currencies.map((e: any) => globalThis.String(e))
        : [],
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: AddCurrencyRes): unknown {
    const obj: any = {};
    if (message.codes?.length) {
      obj.codes = message.codes;
    }
    if (message.currencies?.length) {
      obj.currencies = message.currencies;
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddCurrencyRes>, I>>(base?: I): AddCurrencyRes {
    return AddCurrencyRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddCurrencyRes>, I>>(object: I): AddCurrencyRes {
    const message = createBaseAddCurrencyRes();
    message.codes = object.codes?.map((e) => e) || [];
    message.currencies = object.currencies?.map((e) => e) || [];
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseDeleteCurrencyReq(): DeleteCurrencyReq {
  return { code: "" };
}

export const DeleteCurrencyReq: MessageFns<DeleteCurrencyReq> = {
  encode(message: DeleteCurrencyReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCurrencyReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCurrencyReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCurrencyReq {
    return { code: isSet(object.code) ? globalThis.String(object.code) : "" };
  },

  toJSON(message: DeleteCurrencyReq): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteCurrencyReq>, I>>(base?: I): DeleteCurrencyReq {
    return DeleteCurrencyReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteCurrencyReq>, I>>(object: I): DeleteCurrencyReq {
    const message = createBaseDeleteCurrencyReq();
    message.code = object.code ?? "";
    return message;
  },
};

function createBaseDeleteCurrencyRes(): DeleteCurrencyRes {
  return { base: undefined };
}

export const DeleteCurrencyRes: MessageFns<DeleteCurrencyRes> = {
  encode(message: DeleteCurrencyRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCurrencyRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCurrencyRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCurrencyRes {
    return { base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined };
  },

  toJSON(message: DeleteCurrencyRes): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteCurrencyRes>, I>>(base?: I): DeleteCurrencyRes {
    return DeleteCurrencyRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteCurrencyRes>, I>>(object: I): DeleteCurrencyRes {
    const message = createBaseDeleteCurrencyRes();
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetThemesReq(): GetThemesReq {
  return {};
}

export const GetThemesReq: MessageFns<GetThemesReq> = {
  encode(_: GetThemesReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetThemesReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetThemesReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetThemesReq {
    return {};
  },

  toJSON(_: GetThemesReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetThemesReq>, I>>(base?: I): GetThemesReq {
    return GetThemesReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetThemesReq>, I>>(_: I): GetThemesReq {
    const message = createBaseGetThemesReq();
    return message;
  },
};

function createBaseGetThemesRes(): GetThemesRes {
  return { themes: [], base: undefined };
}

export const GetThemesRes: MessageFns<GetThemesRes> = {
  encode(message: GetThemesRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.themes) {
      Theme.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetThemesRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetThemesRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.themes.push(Theme.decode(reader, reader.uint32()));
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetThemesRes {
    return {
      themes: globalThis.Array.isArray(object?.themes) ? object.themes.map((e: any) => Theme.fromJSON(e)) : [],
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetThemesRes): unknown {
    const obj: any = {};
    if (message.themes?.length) {
      obj.themes = message.themes.map((e) => Theme.toJSON(e));
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetThemesRes>, I>>(base?: I): GetThemesRes {
    return GetThemesRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetThemesRes>, I>>(object: I): GetThemesRes {
    const message = createBaseGetThemesRes();
    message.themes = object.themes?.map((e) => Theme.fromPartial(e)) || [];
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetAccountTypesReq(): GetAccountTypesReq {
  return {};
}

export const GetAccountTypesReq: MessageFns<GetAccountTypesReq> = {
  encode(_: GetAccountTypesReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountTypesReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountTypesReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetAccountTypesReq {
    return {};
  },

  toJSON(_: GetAccountTypesReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountTypesReq>, I>>(base?: I): GetAccountTypesReq {
    return GetAccountTypesReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountTypesReq>, I>>(_: I): GetAccountTypesReq {
    const message = createBaseGetAccountTypesReq();
    return message;
  },
};

function createBaseGetAccountTypesRes(): GetAccountTypesRes {
  return { types: {}, base: undefined };
}

export const GetAccountTypesRes: MessageFns<GetAccountTypesRes> = {
  encode(message: GetAccountTypesRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.types).forEach(([key, value]: [string, AccountTypeConfig]) => {
      GetAccountTypesRes_TypesEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountTypesRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountTypesRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = GetAccountTypesRes_TypesEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.types[entry1.key] = entry1.value;
          }
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccountTypesRes {
    return {
      types: isObject(object.types)
        ? (globalThis.Object.entries(object.types) as [string, any][]).reduce(
          (acc: { [key: number]: AccountTypeConfig }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = AccountTypeConfig.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetAccountTypesRes): unknown {
    const obj: any = {};
    if (message.types) {
      const entries = globalThis.Object.entries(message.types) as [string, AccountTypeConfig][];
      if (entries.length > 0) {
        obj.types = {};
        entries.forEach(([k, v]) => {
          obj.types[k] = AccountTypeConfig.toJSON(v);
        });
      }
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountTypesRes>, I>>(base?: I): GetAccountTypesRes {
    return GetAccountTypesRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountTypesRes>, I>>(object: I): GetAccountTypesRes {
    const message = createBaseGetAccountTypesRes();
    message.types = (globalThis.Object.entries(object.types ?? {}) as [string, AccountTypeConfig][]).reduce(
      (acc: { [key: number]: AccountTypeConfig }, [key, value]: [string, AccountTypeConfig]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = AccountTypeConfig.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetAccountTypesRes_TypesEntry(): GetAccountTypesRes_TypesEntry {
  return { key: 0, value: undefined };
}

export const GetAccountTypesRes_TypesEntry: MessageFns<GetAccountTypesRes_TypesEntry> = {
  encode(message: GetAccountTypesRes_TypesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== undefined) {
      AccountTypeConfig.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountTypesRes_TypesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountTypesRes_TypesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = AccountTypeConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccountTypesRes_TypesEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? AccountTypeConfig.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: GetAccountTypesRes_TypesEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = AccountTypeConfig.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountTypesRes_TypesEntry>, I>>(base?: I): GetAccountTypesRes_TypesEntry {
    return GetAccountTypesRes_TypesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountTypesRes_TypesEntry>, I>>(
    object: I,
  ): GetAccountTypesRes_TypesEntry {
    const message = createBaseGetAccountTypesRes_TypesEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? AccountTypeConfig.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseExchangeRate(): ExchangeRate {
  return { currency: "", rate: "", source: "", updatedAt: "" };
}

export const ExchangeRate: MessageFns<ExchangeRate> = {
  encode(message: ExchangeRate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currency !== "") {
      writer.uint32(10).string(message.currency);
    }
    if (message.rate !== "") {
      writer.uint32(18).string(message.rate);
    }
    if (message.source !== "") {
      writer.uint32(26).string(message.source);
    }
    if (message.updatedAt !== "") {
      writer.uint32(34).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeRate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeRate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rate = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeRate {
    return {
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      rate: isSet(object.rate) ? globalThis.String(object.rate) : "",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
    };
  },

  toJSON(message: ExchangeRate): unknown {
    const obj: any = {};
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.rate !== "") {
      obj.rate = message.rate;
    }
    if (message.source !== "") {
      obj.source = message.source;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeRate>, I>>(base?: I): ExchangeRate {
    return ExchangeRate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeRate>, I>>(object: I): ExchangeRate {
    const message = createBaseExchangeRate();
    message.currency = object.currency ?? "";
    message.rate = object.rate ?? "";
    message.source = object.source ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseGetExchangeRatesReq(): GetExchangeRatesReq {
  return {};
}

export const GetExchangeRatesReq: MessageFns<GetExchangeRatesReq> = {
  encode(_: GetExchangeRatesReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetExchangeRatesReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetExchangeRatesReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetExchangeRatesReq {
    return {};
  },

  toJSON(_: GetExchangeRatesReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetExchangeRatesReq>, I>>(base?: I): GetExchangeRatesReq {
    return GetExchangeRatesReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetExchangeRatesReq>, I>>(_: I): GetExchangeRatesReq {
    const message = createBaseGetExchangeRatesReq();
    return message;
  },
};

function createBaseGetExchangeRatesRes(): GetExchangeRatesRes {
  return { anchor: "", rates: [], base: undefined };
}

export const GetExchangeRatesRes: MessageFns<GetExchangeRatesRes> = {
  encode(message: GetExchangeRatesRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.anchor !== "") {
      writer.uint32(10).string(message.anchor);
    }
    for (const v of message.rates) {
      ExchangeRate.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetExchangeRatesRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetExchangeRatesRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.anchor = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rates.push(ExchangeRate.decode(reader, reader.uint32()));
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetExchangeRatesRes {
    return {
      anchor: isSet(object.anchor) ? globalThis.String(object.anchor) : "",
      rates: globalThis.Array.isArray(object?.rates) ? object.rates.map((e: any) => ExchangeRate.fromJSON(e)) : [],
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetExchangeRatesRes): unknown {
    const obj: any = {};
    if (message.anchor !== "") {
      obj.anchor = message.anchor;
    }
    if (message.rates?.length) {
      obj.rates = message.rates.map((e) => ExchangeRate.toJSON(e));
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetExchangeRatesRes>, I>>(base?: I): GetExchangeRatesRes {
    return GetExchangeRatesRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetExchangeRatesRes>, I>>(object: I): GetExchangeRatesRes {
    const message = createBaseGetExchangeRatesRes();
    message.anchor = object.anchor ?? "";
    message.rates = object.rates?.map((e) => ExchangeRate.fromPartial(e)) || [];
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseSetExchangeRateReq(): SetExchangeRateReq {
  return { currency: "", rate: "" };
}

export const SetExchangeRateReq: MessageFns<SetExchangeRateReq> = {
  encode(message: SetExchangeRateReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currency !== "") {
      writer.uint32(10).string(message.currency);
    }
    if (message.rate !== "") {
      writer.uint32(18).string(message.rate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetExchangeRateReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetExchangeRateReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rate = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetExchangeRateReq {
    return {
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      rate: isSet(object.rate) ? globalThis.String(object.rate) : "",
    };
  },

  toJSON(message: SetExchangeRateReq): unknown {
    const obj: any = {};
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.rate !== "") {
      obj.rate = message.rate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetExchangeRateReq>, I>>(base?: I): SetExchangeRateReq {
    return SetExchangeRateReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetExchangeRateReq>, I>>(object: I): SetExchangeRateReq {
    const message = createBaseSetExchangeRateReq();
    message.currency = object.currency ?? "";
    message.rate = object.rate ?? "";
    return message;
  },
};

function createBaseSetExchangeRateRes(): SetExchangeRateRes {
  return { rate: undefined, base: undefined };
}

export const SetExchangeRateRes: MessageFns<SetExchangeRateRes> = {
  encode(message: SetExchangeRateRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rate !== undefined) {
      ExchangeRate.encode(message.rate, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetExchangeRateRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetExchangeRateRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rate = ExchangeRate.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetExchangeRateRes {
    return {
      rate: isSet(object.rate) ? ExchangeRate.fromJSON(object.rate) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: SetExchangeRateRes): unknown {
    const obj: any = {};
    if (message.rate !== undefined) {
      obj.rate = ExchangeRate.toJSON(message.rate);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetExchangeRateRes>, I>>(base?: I): SetExchangeRateRes {
    return SetExchangeRateRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetExchangeRateRes>, I>>(object: I): SetExchangeRateRes {
    const message = createBaseSetExchangeRateRes();
    message.rate = (object.rate !== undefined && object.rate !== null)
      ? ExchangeRate.fromPartial(object.rate)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

export interface ConfigService {
  /** Get supported currencies */
  ListCurrencies(request: ListCurrenciesReq): Promise<ListCurrenciesRes>;
  /** Add a supported currency */
  AddCurrency(request: AddCurrencyReq): Promise<AddCurrencyRes>;
  /** Remove a supported currency */
  DeleteCurrency(request: DeleteCurrencyReq): Promise<DeleteCurrencyRes>;
  /** Get available themes */
  GetThemes(request: GetThemesReq): Promise<GetThemesRes>;
  /** Get account type definitions */
  GetAccountTypes(request: GetAccountTypesReq): Promise<GetAccountTypesRes>;
  /** Get exchange rates (reference + manual) relative to the anchor currency */
  GetExchangeRates(request: GetExchangeRatesReq): Promise<GetExchangeRatesRes>;
  /** Set a manual exchange-rate override for a currency */
  SetExchangeRate(request: SetExchangeRateReq): Promise<SetExchangeRateRes>;
}

export const ConfigServiceServiceName = "config.v1.ConfigService";
export class ConfigServiceClientImpl implements ConfigService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ConfigServiceServiceName;
    this.rpc = rpc;
    this.ListCurrencies = this.ListCurrencies.bind(this);
    this.AddCurrency = this.AddCurrency.bind(this);
    this.DeleteCurrency = this.DeleteCurrency.bind(this);
    this.GetThemes = this.GetThemes.bind(this);
    this.GetAccountTypes = this.GetAccountTypes.bind(this);
    this.GetExchangeRates = this.GetExchangeRates.bind(this);
    this.SetExchangeRate = this.SetExchangeRate.bind(this);
  }
  ListCurrencies(request: ListCurrenciesReq): Promise<ListCurrenciesRes> {
    const data = ListCurrenciesReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListCurrencies", data);
    return promise.then((data) => ListCurrenciesRes.decode(new BinaryReader(data)));
  }

  AddCurrency(request: AddCurrencyReq): Promise<AddCurrencyRes> {
    const data = AddCurrencyReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "AddCurrency", data);
    return promise.then((data) => AddCurrencyRes.decode(new BinaryReader(data)));
  }

  DeleteCurrency(request: DeleteCurrencyReq): Promise<DeleteCurrencyRes> {
    const data = DeleteCurrencyReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteCurrency", data);
    return promise.then((data) => DeleteCurrencyRes.decode(new BinaryReader(data)));
  }

  GetThemes(request: GetThemesReq): Promise<GetThemesRes> {
    const data = GetThemesReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetThemes", data);
    return promise.then((data) => GetThemesRes.decode(new BinaryReader(data)));
  }

  GetAccountTypes(request: GetAccountTypesReq): Promise<GetAccountTypesRes> {
    const data = GetAccountTypesReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAccountTypes", data);
    return promise.then((data) => GetAccountTypesRes.decode(new BinaryReader(data)));
  }

  GetExchangeRates(request: GetExchangeRatesReq): Promise<GetExchangeRatesRes> {
    const data = GetExchangeRatesReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetExchangeRates", data);
    return promise.then((data) => GetExchangeRatesRes.decode(new BinaryReader(data)));
  }

  SetExchangeRate(request: SetExchangeRateReq): Promise<SetExchangeRateRes> {
    const data = SetExchangeRateReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetExchangeRate", data);
    return promise.then((data) => SetExchangeRateRes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
