// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: hello/v1/hello.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BaseResponse } from "../../base/base";

export const protobufPackage = "hello.v1";

export interface HelloReq {
}

export interface HelloRes {
  base: BaseResponse | undefined;
}

function createBaseHelloReq(): HelloReq {
  return {};
}

export const HelloReq: MessageFns<HelloReq> = {
  encode(_: HelloReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HelloReq {
    return {};
  },

  toJSON(_: HelloReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloReq>, I>>(base?: I): HelloReq {
    return HelloReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloReq>, I>>(_: I): HelloReq {
    const message = createBaseHelloReq();
    return message;
  },
};

function createBaseHelloRes(): HelloRes {
  return { base: undefined };
}

export const HelloRes: MessageFns<HelloRes> = {
  encode(message: HelloRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HelloRes {
    return { base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined };
  },

  toJSON(message: HelloRes): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloRes>, I>>(base?: I): HelloRes {
    return HelloRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloRes>, I>>(object: I): HelloRes {
    const message = createBaseHelloRes();
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

export interface HelloService {
  /** You first hello api */
  Hello(request: HelloReq): Promise<HelloRes>;
}

export const HelloServiceServiceName = "hello.v1.HelloService";
export class HelloServiceClientImpl implements HelloService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || HelloServiceServiceName;
    this.rpc = rpc;
    this.Hello = this.Hello.bind(this);
  }
  Hello(request: HelloReq): Promise<HelloRes> {
    const data = HelloReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "Hello", data);
    return promise.then((data) => HelloRes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
