// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: dashboard/v1/dashboard.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BaseResponse, Money } from "../../base/base";

export const protobufPackage = "dashboard.v1";

export interface DashboardSummary {
  assets: Money | undefined;
  liabilities: Money | undefined;
  netWorth: Money | undefined;
}

export interface MonthlyStats {
  income: Money | undefined;
  expense: Money | undefined;
}

export interface DailyBalance {
  /** Date string */
  date: string;
  /** Account ID -> Balance */
  balances: { [key: string]: Money };
}

export interface DailyBalance_BalancesEntry {
  key: string;
  value: Money | undefined;
}

export interface GetDashboardSummaryReq {
}

export interface GetDashboardSummaryRes {
  summary: DashboardSummary | undefined;
  base: BaseResponse | undefined;
}

export interface GetMonthlyStatsReq {
}

export interface GetMonthlyStatsRes {
  stats: MonthlyStats | undefined;
  base: BaseResponse | undefined;
}

export interface GetBalanceTrendReq {
  accounts: string[];
}

export interface GetBalanceTrendRes {
  data: DailyBalance[];
  base: BaseResponse | undefined;
}

function createBaseDashboardSummary(): DashboardSummary {
  return { assets: undefined, liabilities: undefined, netWorth: undefined };
}

export const DashboardSummary: MessageFns<DashboardSummary> = {
  encode(message: DashboardSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.assets !== undefined) {
      Money.encode(message.assets, writer.uint32(10).fork()).join();
    }
    if (message.liabilities !== undefined) {
      Money.encode(message.liabilities, writer.uint32(18).fork()).join();
    }
    if (message.netWorth !== undefined) {
      Money.encode(message.netWorth, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DashboardSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDashboardSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.assets = Money.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.liabilities = Money.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.netWorth = Money.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DashboardSummary {
    return {
      assets: isSet(object.assets) ? Money.fromJSON(object.assets) : undefined,
      liabilities: isSet(object.liabilities) ? Money.fromJSON(object.liabilities) : undefined,
      netWorth: isSet(object.netWorth) ? Money.fromJSON(object.netWorth) : undefined,
    };
  },

  toJSON(message: DashboardSummary): unknown {
    const obj: any = {};
    if (message.assets !== undefined) {
      obj.assets = Money.toJSON(message.assets);
    }
    if (message.liabilities !== undefined) {
      obj.liabilities = Money.toJSON(message.liabilities);
    }
    if (message.netWorth !== undefined) {
      obj.netWorth = Money.toJSON(message.netWorth);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DashboardSummary>, I>>(base?: I): DashboardSummary {
    return DashboardSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DashboardSummary>, I>>(object: I): DashboardSummary {
    const message = createBaseDashboardSummary();
    message.assets = (object.assets !== undefined && object.assets !== null)
      ? Money.fromPartial(object.assets)
      : undefined;
    message.liabilities = (object.liabilities !== undefined && object.liabilities !== null)
      ? Money.fromPartial(object.liabilities)
      : undefined;
    message.netWorth = (object.netWorth !== undefined && object.netWorth !== null)
      ? Money.fromPartial(object.netWorth)
      : undefined;
    return message;
  },
};

function createBaseMonthlyStats(): MonthlyStats {
  return { income: undefined, expense: undefined };
}

export const MonthlyStats: MessageFns<MonthlyStats> = {
  encode(message: MonthlyStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.income !== undefined) {
      Money.encode(message.income, writer.uint32(10).fork()).join();
    }
    if (message.expense !== undefined) {
      Money.encode(message.expense, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MonthlyStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMonthlyStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.income = Money.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.expense = Money.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MonthlyStats {
    return {
      income: isSet(object.income) ? Money.fromJSON(object.income) : undefined,
      expense: isSet(object.expense) ? Money.fromJSON(object.expense) : undefined,
    };
  },

  toJSON(message: MonthlyStats): unknown {
    const obj: any = {};
    if (message.income !== undefined) {
      obj.income = Money.toJSON(message.income);
    }
    if (message.expense !== undefined) {
      obj.expense = Money.toJSON(message.expense);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MonthlyStats>, I>>(base?: I): MonthlyStats {
    return MonthlyStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MonthlyStats>, I>>(object: I): MonthlyStats {
    const message = createBaseMonthlyStats();
    message.income = (object.income !== undefined && object.income !== null)
      ? Money.fromPartial(object.income)
      : undefined;
    message.expense = (object.expense !== undefined && object.expense !== null)
      ? Money.fromPartial(object.expense)
      : undefined;
    return message;
  },
};

function createBaseDailyBalance(): DailyBalance {
  return { date: "", balances: {} };
}

export const DailyBalance: MessageFns<DailyBalance> = {
  encode(message: DailyBalance, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    globalThis.Object.entries(message.balances).forEach(([key, value]: [string, Money]) => {
      DailyBalance_BalancesEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DailyBalance {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDailyBalance();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = DailyBalance_BalancesEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.balances[entry2.key] = entry2.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DailyBalance {
    return {
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      balances: isObject(object.balances)
        ? (globalThis.Object.entries(object.balances) as [string, any][]).reduce(
          (acc: { [key: string]: Money }, [key, value]: [string, any]) => {
            acc[key] = Money.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: DailyBalance): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.balances) {
      const entries = globalThis.Object.entries(message.balances) as [string, Money][];
      if (entries.length > 0) {
        obj.balances = {};
        entries.forEach(([k, v]) => {
          obj.balances[k] = Money.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DailyBalance>, I>>(base?: I): DailyBalance {
    return DailyBalance.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DailyBalance>, I>>(object: I): DailyBalance {
    const message = createBaseDailyBalance();
    message.date = object.date ?? "";
    message.balances = (globalThis.Object.entries(object.balances ?? {}) as [string, Money][]).reduce(
      (acc: { [key: string]: Money }, [key, value]: [string, Money]) => {
        if (value !== undefined) {
          acc[key] = Money.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDailyBalance_BalancesEntry(): DailyBalance_BalancesEntry {
  return { key: "", value: undefined };
}

export const DailyBalance_BalancesEntry: MessageFns<DailyBalance_BalancesEntry> = {
  encode(message: DailyBalance_BalancesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Money.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DailyBalance_BalancesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDailyBalance_BalancesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Money.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DailyBalance_BalancesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Money.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: DailyBalance_BalancesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Money.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DailyBalance_BalancesEntry>, I>>(base?: I): DailyBalance_BalancesEntry {
    return DailyBalance_BalancesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DailyBalance_BalancesEntry>, I>>(object: I): DailyBalance_BalancesEntry {
    const message = createBaseDailyBalance_BalancesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Money.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseGetDashboardSummaryReq(): GetDashboardSummaryReq {
  return {};
}

export const GetDashboardSummaryReq: MessageFns<GetDashboardSummaryReq> = {
  encode(_: GetDashboardSummaryReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDashboardSummaryReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDashboardSummaryReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetDashboardSummaryReq {
    return {};
  },

  toJSON(_: GetDashboardSummaryReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetDashboardSummaryReq>, I>>(base?: I): GetDashboardSummaryReq {
    return GetDashboardSummaryReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetDashboardSummaryReq>, I>>(_: I): GetDashboardSummaryReq {
    const message = createBaseGetDashboardSummaryReq();
    return message;
  },
};

function createBaseGetDashboardSummaryRes(): GetDashboardSummaryRes {
  return { summary: undefined, base: undefined };
}

export const GetDashboardSummaryRes: MessageFns<GetDashboardSummaryRes> = {
  encode(message: GetDashboardSummaryRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.summary !== undefined) {
      DashboardSummary.encode(message.summary, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDashboardSummaryRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDashboardSummaryRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.summary = DashboardSummary.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDashboardSummaryRes {
    return {
      summary: isSet(object.summary) ? DashboardSummary.fromJSON(object.summary) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetDashboardSummaryRes): unknown {
    const obj: any = {};
    if (message.summary !== undefined) {
      obj.summary = DashboardSummary.toJSON(message.summary);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetDashboardSummaryRes>, I>>(base?: I): GetDashboardSummaryRes {
    return GetDashboardSummaryRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetDashboardSummaryRes>, I>>(object: I): GetDashboardSummaryRes {
    const message = createBaseGetDashboardSummaryRes();
    message.summary = (object.summary !== undefined && object.summary !== null)
      ? DashboardSummary.fromPartial(object.summary)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetMonthlyStatsReq(): GetMonthlyStatsReq {
  return {};
}

export const GetMonthlyStatsReq: MessageFns<GetMonthlyStatsReq> = {
  encode(_: GetMonthlyStatsReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMonthlyStatsReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMonthlyStatsReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetMonthlyStatsReq {
    return {};
  },

  toJSON(_: GetMonthlyStatsReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMonthlyStatsReq>, I>>(base?: I): GetMonthlyStatsReq {
    return GetMonthlyStatsReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMonthlyStatsReq>, I>>(_: I): GetMonthlyStatsReq {
    const message = createBaseGetMonthlyStatsReq();
    return message;
  },
};

function createBaseGetMonthlyStatsRes(): GetMonthlyStatsRes {
  return { stats: undefined, base: undefined };
}

export const GetMonthlyStatsRes: MessageFns<GetMonthlyStatsRes> = {
  encode(message: GetMonthlyStatsRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stats !== undefined) {
      MonthlyStats.encode(message.stats, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMonthlyStatsRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMonthlyStatsRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stats = MonthlyStats.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMonthlyStatsRes {
    return {
      stats: isSet(object.stats) ? MonthlyStats.fromJSON(object.stats) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetMonthlyStatsRes): unknown {
    const obj: any = {};
    if (message.stats !== undefined) {
      obj.stats = MonthlyStats.toJSON(message.stats);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMonthlyStatsRes>, I>>(base?: I): GetMonthlyStatsRes {
    return GetMonthlyStatsRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMonthlyStatsRes>, I>>(object: I): GetMonthlyStatsRes {
    const message = createBaseGetMonthlyStatsRes();
    message.stats = (object.stats !== undefined && object.stats !== null)
      ? MonthlyStats.fromPartial(object.stats)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetBalanceTrendReq(): GetBalanceTrendReq {
  return { accounts: [] };
}

export const GetBalanceTrendReq: MessageFns<GetBalanceTrendReq> = {
  encode(message: GetBalanceTrendReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.accounts) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalanceTrendReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalanceTrendReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accounts.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalanceTrendReq {
    return {
      accounts: globalThis.Array.isArray(object?.accounts) ? object.accounts.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: GetBalanceTrendReq): unknown {
    const obj: any = {};
    if (message.accounts?.length) {
      obj.accounts = message.accounts;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBalanceTrendReq>, I>>(base?: I): GetBalanceTrendReq {
    return GetBalanceTrendReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBalanceTrendReq>, I>>(object: I): GetBalanceTrendReq {
    const message = createBaseGetBalanceTrendReq();
    message.accounts = object.accounts?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetBalanceTrendRes(): GetBalanceTrendRes {
  return { data: [], base: undefined };
}

export const GetBalanceTrendRes: MessageFns<GetBalanceTrendRes> = {
  encode(message: GetBalanceTrendRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      DailyBalance.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalanceTrendRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalanceTrendRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(DailyBalance.decode(reader, reader.uint32()));
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalanceTrendRes {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => DailyBalance.fromJSON(e)) : [],
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetBalanceTrendRes): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => DailyBalance.toJSON(e));
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBalanceTrendRes>, I>>(base?: I): GetBalanceTrendRes {
    return GetBalanceTrendRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBalanceTrendRes>, I>>(object: I): GetBalanceTrendRes {
    const message = createBaseGetBalanceTrendRes();
    message.data = object.data?.map((e) => DailyBalance.fromPartial(e)) || [];
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

export interface DashboardService {
  /** Get dashboard summary */
  GetDashboardSummary(request: GetDashboardSummaryReq): Promise<GetDashboardSummaryRes>;
  /** Get monthly income and expense statistics */
  GetMonthlyStats(request: GetMonthlyStatsReq): Promise<GetMonthlyStatsRes>;
  /** Get balance trend data */
  GetBalanceTrend(request: GetBalanceTrendReq): Promise<GetBalanceTrendRes>;
}

export const DashboardServiceServiceName = "dashboard.v1.DashboardService";
export class DashboardServiceClientImpl implements DashboardService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || DashboardServiceServiceName;
    this.rpc = rpc;
    this.GetDashboardSummary = this.GetDashboardSummary.bind(this);
    this.GetMonthlyStats = this.GetMonthlyStats.bind(this);
    this.GetBalanceTrend = this.GetBalanceTrend.bind(this);
  }
  GetDashboardSummary(request: GetDashboardSummaryReq): Promise<GetDashboardSummaryRes> {
    const data = GetDashboardSummaryReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetDashboardSummary", data);
    return promise.then((data) => GetDashboardSummaryRes.decode(new BinaryReader(data)));
  }

  GetMonthlyStats(request: GetMonthlyStatsReq): Promise<GetMonthlyStatsRes> {
    const data = GetMonthlyStatsReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetMonthlyStats", data);
    return promise.then((data) => GetMonthlyStatsRes.decode(new BinaryReader(data)));
  }

  GetBalanceTrend(request: GetBalanceTrendReq): Promise<GetBalanceTrendRes> {
    const data = GetBalanceTrendReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBalanceTrend", data);
    return promise.then((data) => GetBalanceTrendRes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
