// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: auth/v1/auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BaseResponse } from "../../base/base";
import { User } from "../../user/v1/user";

export const protobufPackage = "auth.v1";

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user:
    | User
    | undefined;
  /** ALE session key (hex encoded) */
  sessionKey: string;
}

export interface LoginReq {
  email: string;
  password: string;
  code: string;
  cfTurnstileResponse: string;
}

export interface LoginRes {
  auth: AuthResponse | undefined;
  base: BaseResponse | undefined;
}

export interface RegisterReq {
  email: string;
  password: string;
  nickname: string;
  cfTurnstileResponse: string;
}

export interface RegisterRes {
  auth: AuthResponse | undefined;
  base: BaseResponse | undefined;
}

export interface LogoutReq {
}

export interface LogoutRes {
  base: BaseResponse | undefined;
}

export interface RefreshTokenReq {
  refreshToken: string;
}

export interface RefreshTokenRes {
  accessToken: string;
  refreshToken: string;
  /** ALE session key (hex encoded) */
  sessionKey: string;
  base: BaseResponse | undefined;
}

export interface TwoFactorSecret {
  secret: string;
  url: string;
}

export interface Generate2FAReq {
}

export interface Generate2FARes {
  secret: TwoFactorSecret | undefined;
  base: BaseResponse | undefined;
}

export interface Enable2FAReq {
  code: string;
}

export interface Enable2FARes {
  base: BaseResponse | undefined;
}

export interface Disable2FAReq {
  code: string;
  password: string;
}

export interface Disable2FARes {
  base: BaseResponse | undefined;
}

function createBaseAuthResponse(): AuthResponse {
  return { accessToken: "", refreshToken: "", user: undefined, sessionKey: "" };
}

export const AuthResponse: MessageFns<AuthResponse> = {
  encode(message: AuthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    if (message.refreshToken !== "") {
      writer.uint32(18).string(message.refreshToken);
    }
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(26).fork()).join();
    }
    if (message.sessionKey !== "") {
      writer.uint32(34).string(message.sessionKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sessionKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthResponse {
    return {
      accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "",
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "",
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
      sessionKey: isSet(object.sessionKey) ? globalThis.String(object.sessionKey) : "",
    };
  },

  toJSON(message: AuthResponse): unknown {
    const obj: any = {};
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    if (message.sessionKey !== "") {
      obj.sessionKey = message.sessionKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthResponse>, I>>(base?: I): AuthResponse {
    return AuthResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthResponse>, I>>(object: I): AuthResponse {
    const message = createBaseAuthResponse();
    message.accessToken = object.accessToken ?? "";
    message.refreshToken = object.refreshToken ?? "";
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    message.sessionKey = object.sessionKey ?? "";
    return message;
  },
};

function createBaseLoginReq(): LoginReq {
  return { email: "", password: "", code: "", cfTurnstileResponse: "" };
}

export const LoginReq: MessageFns<LoginReq> = {
  encode(message: LoginReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.code !== "") {
      writer.uint32(26).string(message.code);
    }
    if (message.cfTurnstileResponse !== "") {
      writer.uint32(34).string(message.cfTurnstileResponse);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cfTurnstileResponse = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginReq {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      cfTurnstileResponse: isSet(object.cfTurnstileResponse) ? globalThis.String(object.cfTurnstileResponse) : "",
    };
  },

  toJSON(message: LoginReq): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.cfTurnstileResponse !== "") {
      obj.cfTurnstileResponse = message.cfTurnstileResponse;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginReq>, I>>(base?: I): LoginReq {
    return LoginReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginReq>, I>>(object: I): LoginReq {
    const message = createBaseLoginReq();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    message.code = object.code ?? "";
    message.cfTurnstileResponse = object.cfTurnstileResponse ?? "";
    return message;
  },
};

function createBaseLoginRes(): LoginRes {
  return { auth: undefined, base: undefined };
}

export const LoginRes: MessageFns<LoginRes> = {
  encode(message: LoginRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.auth !== undefined) {
      AuthResponse.encode(message.auth, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.auth = AuthResponse.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRes {
    return {
      auth: isSet(object.auth) ? AuthResponse.fromJSON(object.auth) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: LoginRes): unknown {
    const obj: any = {};
    if (message.auth !== undefined) {
      obj.auth = AuthResponse.toJSON(message.auth);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRes>, I>>(base?: I): LoginRes {
    return LoginRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRes>, I>>(object: I): LoginRes {
    const message = createBaseLoginRes();
    message.auth = (object.auth !== undefined && object.auth !== null)
      ? AuthResponse.fromPartial(object.auth)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseRegisterReq(): RegisterReq {
  return { email: "", password: "", nickname: "", cfTurnstileResponse: "" };
}

export const RegisterReq: MessageFns<RegisterReq> = {
  encode(message: RegisterReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.nickname !== "") {
      writer.uint32(26).string(message.nickname);
    }
    if (message.cfTurnstileResponse !== "") {
      writer.uint32(34).string(message.cfTurnstileResponse);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cfTurnstileResponse = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterReq {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
      cfTurnstileResponse: isSet(object.cfTurnstileResponse) ? globalThis.String(object.cfTurnstileResponse) : "",
    };
  },

  toJSON(message: RegisterReq): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    if (message.cfTurnstileResponse !== "") {
      obj.cfTurnstileResponse = message.cfTurnstileResponse;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterReq>, I>>(base?: I): RegisterReq {
    return RegisterReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterReq>, I>>(object: I): RegisterReq {
    const message = createBaseRegisterReq();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    message.nickname = object.nickname ?? "";
    message.cfTurnstileResponse = object.cfTurnstileResponse ?? "";
    return message;
  },
};

function createBaseRegisterRes(): RegisterRes {
  return { auth: undefined, base: undefined };
}

export const RegisterRes: MessageFns<RegisterRes> = {
  encode(message: RegisterRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.auth !== undefined) {
      AuthResponse.encode(message.auth, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.auth = AuthResponse.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterRes {
    return {
      auth: isSet(object.auth) ? AuthResponse.fromJSON(object.auth) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: RegisterRes): unknown {
    const obj: any = {};
    if (message.auth !== undefined) {
      obj.auth = AuthResponse.toJSON(message.auth);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterRes>, I>>(base?: I): RegisterRes {
    return RegisterRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterRes>, I>>(object: I): RegisterRes {
    const message = createBaseRegisterRes();
    message.auth = (object.auth !== undefined && object.auth !== null)
      ? AuthResponse.fromPartial(object.auth)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseLogoutReq(): LogoutReq {
  return {};
}

export const LogoutReq: MessageFns<LogoutReq> = {
  encode(_: LogoutReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LogoutReq {
    return {};
  },

  toJSON(_: LogoutReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutReq>, I>>(base?: I): LogoutReq {
    return LogoutReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutReq>, I>>(_: I): LogoutReq {
    const message = createBaseLogoutReq();
    return message;
  },
};

function createBaseLogoutRes(): LogoutRes {
  return { base: undefined };
}

export const LogoutRes: MessageFns<LogoutRes> = {
  encode(message: LogoutRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutRes {
    return { base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined };
  },

  toJSON(message: LogoutRes): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutRes>, I>>(base?: I): LogoutRes {
    return LogoutRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutRes>, I>>(object: I): LogoutRes {
    const message = createBaseLogoutRes();
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseRefreshTokenReq(): RefreshTokenReq {
  return { refreshToken: "" };
}

export const RefreshTokenReq: MessageFns<RefreshTokenReq> = {
  encode(message: RefreshTokenReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refreshToken !== "") {
      writer.uint32(10).string(message.refreshToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshTokenReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshTokenReq {
    return { refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "" };
  },

  toJSON(message: RefreshTokenReq): unknown {
    const obj: any = {};
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshTokenReq>, I>>(base?: I): RefreshTokenReq {
    return RefreshTokenReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenReq>, I>>(object: I): RefreshTokenReq {
    const message = createBaseRefreshTokenReq();
    message.refreshToken = object.refreshToken ?? "";
    return message;
  },
};

function createBaseRefreshTokenRes(): RefreshTokenRes {
  return { accessToken: "", refreshToken: "", sessionKey: "", base: undefined };
}

export const RefreshTokenRes: MessageFns<RefreshTokenRes> = {
  encode(message: RefreshTokenRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    if (message.refreshToken !== "") {
      writer.uint32(18).string(message.refreshToken);
    }
    if (message.sessionKey !== "") {
      writer.uint32(26).string(message.sessionKey);
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshTokenRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sessionKey = reader.string();
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshTokenRes {
    return {
      accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "",
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "",
      sessionKey: isSet(object.sessionKey) ? globalThis.String(object.sessionKey) : "",
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: RefreshTokenRes): unknown {
    const obj: any = {};
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    if (message.sessionKey !== "") {
      obj.sessionKey = message.sessionKey;
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshTokenRes>, I>>(base?: I): RefreshTokenRes {
    return RefreshTokenRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenRes>, I>>(object: I): RefreshTokenRes {
    const message = createBaseRefreshTokenRes();
    message.accessToken = object.accessToken ?? "";
    message.refreshToken = object.refreshToken ?? "";
    message.sessionKey = object.sessionKey ?? "";
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseTwoFactorSecret(): TwoFactorSecret {
  return { secret: "", url: "" };
}

export const TwoFactorSecret: MessageFns<TwoFactorSecret> = {
  encode(message: TwoFactorSecret, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.secret !== "") {
      writer.uint32(10).string(message.secret);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TwoFactorSecret {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTwoFactorSecret();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.secret = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TwoFactorSecret {
    return {
      secret: isSet(object.secret) ? globalThis.String(object.secret) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
    };
  },

  toJSON(message: TwoFactorSecret): unknown {
    const obj: any = {};
    if (message.secret !== "") {
      obj.secret = message.secret;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TwoFactorSecret>, I>>(base?: I): TwoFactorSecret {
    return TwoFactorSecret.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TwoFactorSecret>, I>>(object: I): TwoFactorSecret {
    const message = createBaseTwoFactorSecret();
    message.secret = object.secret ?? "";
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseGenerate2FAReq(): Generate2FAReq {
  return {};
}

export const Generate2FAReq: MessageFns<Generate2FAReq> = {
  encode(_: Generate2FAReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Generate2FAReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerate2FAReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Generate2FAReq {
    return {};
  },

  toJSON(_: Generate2FAReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Generate2FAReq>, I>>(base?: I): Generate2FAReq {
    return Generate2FAReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Generate2FAReq>, I>>(_: I): Generate2FAReq {
    const message = createBaseGenerate2FAReq();
    return message;
  },
};

function createBaseGenerate2FARes(): Generate2FARes {
  return { secret: undefined, base: undefined };
}

export const Generate2FARes: MessageFns<Generate2FARes> = {
  encode(message: Generate2FARes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.secret !== undefined) {
      TwoFactorSecret.encode(message.secret, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Generate2FARes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerate2FARes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.secret = TwoFactorSecret.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Generate2FARes {
    return {
      secret: isSet(object.secret) ? TwoFactorSecret.fromJSON(object.secret) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: Generate2FARes): unknown {
    const obj: any = {};
    if (message.secret !== undefined) {
      obj.secret = TwoFactorSecret.toJSON(message.secret);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Generate2FARes>, I>>(base?: I): Generate2FARes {
    return Generate2FARes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Generate2FARes>, I>>(object: I): Generate2FARes {
    const message = createBaseGenerate2FARes();
    message.secret = (object.secret !== undefined && object.secret !== null)
      ? TwoFactorSecret.fromPartial(object.secret)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseEnable2FAReq(): Enable2FAReq {
  return { code: "" };
}

export const Enable2FAReq: MessageFns<Enable2FAReq> = {
  encode(message: Enable2FAReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Enable2FAReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnable2FAReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Enable2FAReq {
    return { code: isSet(object.code) ? globalThis.String(object.code) : "" };
  },

  toJSON(message: Enable2FAReq): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Enable2FAReq>, I>>(base?: I): Enable2FAReq {
    return Enable2FAReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Enable2FAReq>, I>>(object: I): Enable2FAReq {
    const message = createBaseEnable2FAReq();
    message.code = object.code ?? "";
    return message;
  },
};

function createBaseEnable2FARes(): Enable2FARes {
  return { base: undefined };
}

export const Enable2FARes: MessageFns<Enable2FARes> = {
  encode(message: Enable2FARes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Enable2FARes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnable2FARes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Enable2FARes {
    return { base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined };
  },

  toJSON(message: Enable2FARes): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Enable2FARes>, I>>(base?: I): Enable2FARes {
    return Enable2FARes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Enable2FARes>, I>>(object: I): Enable2FARes {
    const message = createBaseEnable2FARes();
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseDisable2FAReq(): Disable2FAReq {
  return { code: "", password: "" };
}

export const Disable2FAReq: MessageFns<Disable2FAReq> = {
  encode(message: Disable2FAReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Disable2FAReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisable2FAReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Disable2FAReq {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: Disable2FAReq): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Disable2FAReq>, I>>(base?: I): Disable2FAReq {
    return Disable2FAReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Disable2FAReq>, I>>(object: I): Disable2FAReq {
    const message = createBaseDisable2FAReq();
    message.code = object.code ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseDisable2FARes(): Disable2FARes {
  return { base: undefined };
}

export const Disable2FARes: MessageFns<Disable2FARes> = {
  encode(message: Disable2FARes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Disable2FARes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisable2FARes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Disable2FARes {
    return { base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined };
  },

  toJSON(message: Disable2FARes): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Disable2FARes>, I>>(base?: I): Disable2FARes {
    return Disable2FARes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Disable2FARes>, I>>(object: I): Disable2FARes {
    const message = createBaseDisable2FARes();
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

export interface AuthService {
  /** User login */
  Login(request: LoginReq): Promise<LoginRes>;
  /** User registration */
  Register(request: RegisterReq): Promise<RegisterRes>;
  /** User logout */
  Logout(request: LogoutReq): Promise<LogoutRes>;
  /** Refresh access token */
  RefreshToken(request: RefreshTokenReq): Promise<RefreshTokenRes>;
  /** Generate 2FA secret */
  Generate2FA(request: Generate2FAReq): Promise<Generate2FARes>;
  /** Enable 2FA */
  Enable2FA(request: Enable2FAReq): Promise<Enable2FARes>;
  /** Disable 2FA */
  Disable2FA(request: Disable2FAReq): Promise<Disable2FARes>;
}

export const AuthServiceServiceName = "auth.v1.AuthService";
export class AuthServiceClientImpl implements AuthService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AuthServiceServiceName;
    this.rpc = rpc;
    this.Login = this.Login.bind(this);
    this.Register = this.Register.bind(this);
    this.Logout = this.Logout.bind(this);
    this.RefreshToken = this.RefreshToken.bind(this);
    this.Generate2FA = this.Generate2FA.bind(this);
    this.Enable2FA = this.Enable2FA.bind(this);
    this.Disable2FA = this.Disable2FA.bind(this);
  }
  Login(request: LoginReq): Promise<LoginRes> {
    const data = LoginReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "Login", data);
    return promise.then((data) => LoginRes.decode(new BinaryReader(data)));
  }

  Register(request: RegisterReq): Promise<RegisterRes> {
    const data = RegisterReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "Register", data);
    return promise.then((data) => RegisterRes.decode(new BinaryReader(data)));
  }

  Logout(request: LogoutReq): Promise<LogoutRes> {
    const data = LogoutReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "Logout", data);
    return promise.then((data) => LogoutRes.decode(new BinaryReader(data)));
  }

  RefreshToken(request: RefreshTokenReq): Promise<RefreshTokenRes> {
    const data = RefreshTokenReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "RefreshToken", data);
    return promise.then((data) => RefreshTokenRes.decode(new BinaryReader(data)));
  }

  Generate2FA(request: Generate2FAReq): Promise<Generate2FARes> {
    const data = Generate2FAReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "Generate2FA", data);
    return promise.then((data) => Generate2FARes.decode(new BinaryReader(data)));
  }

  Enable2FA(request: Enable2FAReq): Promise<Enable2FARes> {
    const data = Enable2FAReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "Enable2FA", data);
    return promise.then((data) => Enable2FARes.decode(new BinaryReader(data)));
  }

  Disable2FA(request: Disable2FAReq): Promise<Disable2FARes> {
    const data = Disable2FAReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "Disable2FA", data);
    return promise.then((data) => Disable2FARes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
