// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: data/v1/data.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BaseResponse } from "../../base/base";
import { Task } from "../../task/v1/task";

export const protobufPackage = "data.v1";

export interface ExportParams {
  startDate: string;
  endDate: string;
}

export interface ExportDataReq {
  params: ExportParams | undefined;
}

export interface ExportDataRes {
  taskId: string;
  base: BaseResponse | undefined;
}

export interface ImportDataReq {
  /** File content in bytes */
  fileContent: Uint8Array;
  fileName: string;
}

export interface ImportDataRes {
  taskId: string;
  base: BaseResponse | undefined;
}

export interface DownloadExportReq {
  taskId: string;
}

export interface DownloadExportRes {
  /** Metadata could be added here */
  fileContent: Uint8Array;
}

export interface GetExportStatusReq {
  taskId: string;
}

export interface GetExportStatusRes {
  task: Task | undefined;
  base: BaseResponse | undefined;
}

function createBaseExportParams(): ExportParams {
  return { startDate: "", endDate: "" };
}

export const ExportParams: MessageFns<ExportParams> = {
  encode(message: ExportParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startDate !== "") {
      writer.uint32(10).string(message.startDate);
    }
    if (message.endDate !== "") {
      writer.uint32(18).string(message.endDate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExportParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.startDate = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.endDate = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExportParams {
    return {
      startDate: isSet(object.startDate) ? globalThis.String(object.startDate) : "",
      endDate: isSet(object.endDate) ? globalThis.String(object.endDate) : "",
    };
  },

  toJSON(message: ExportParams): unknown {
    const obj: any = {};
    if (message.startDate !== "") {
      obj.startDate = message.startDate;
    }
    if (message.endDate !== "") {
      obj.endDate = message.endDate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExportParams>, I>>(base?: I): ExportParams {
    return ExportParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExportParams>, I>>(object: I): ExportParams {
    const message = createBaseExportParams();
    message.startDate = object.startDate ?? "";
    message.endDate = object.endDate ?? "";
    return message;
  },
};

function createBaseExportDataReq(): ExportDataReq {
  return { params: undefined };
}

export const ExportDataReq: MessageFns<ExportDataReq> = {
  encode(message: ExportDataReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      ExportParams.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExportDataReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportDataReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = ExportParams.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExportDataReq {
    return { params: isSet(object.params) ? ExportParams.fromJSON(object.params) : undefined };
  },

  toJSON(message: ExportDataReq): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = ExportParams.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExportDataReq>, I>>(base?: I): ExportDataReq {
    return ExportDataReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExportDataReq>, I>>(object: I): ExportDataReq {
    const message = createBaseExportDataReq();
    message.params = (object.params !== undefined && object.params !== null)
      ? ExportParams.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseExportDataRes(): ExportDataRes {
  return { taskId: "", base: undefined };
}

export const ExportDataRes: MessageFns<ExportDataRes> = {
  encode(message: ExportDataRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExportDataRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportDataRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExportDataRes {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "",
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: ExportDataRes): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExportDataRes>, I>>(base?: I): ExportDataRes {
    return ExportDataRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExportDataRes>, I>>(object: I): ExportDataRes {
    const message = createBaseExportDataRes();
    message.taskId = object.taskId ?? "";
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseImportDataReq(): ImportDataReq {
  return { fileContent: new Uint8Array(0), fileName: "" };
}

export const ImportDataReq: MessageFns<ImportDataReq> = {
  encode(message: ImportDataReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fileContent.length !== 0) {
      writer.uint32(10).bytes(message.fileContent);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ImportDataReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseImportDataReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fileContent = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ImportDataReq {
    return {
      fileContent: isSet(object.fileContent) ? bytesFromBase64(object.fileContent) : new Uint8Array(0),
      fileName: isSet(object.fileName) ? globalThis.String(object.fileName) : "",
    };
  },

  toJSON(message: ImportDataReq): unknown {
    const obj: any = {};
    if (message.fileContent.length !== 0) {
      obj.fileContent = base64FromBytes(message.fileContent);
    }
    if (message.fileName !== "") {
      obj.fileName = message.fileName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ImportDataReq>, I>>(base?: I): ImportDataReq {
    return ImportDataReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ImportDataReq>, I>>(object: I): ImportDataReq {
    const message = createBaseImportDataReq();
    message.fileContent = object.fileContent ?? new Uint8Array(0);
    message.fileName = object.fileName ?? "";
    return message;
  },
};

function createBaseImportDataRes(): ImportDataRes {
  return { taskId: "", base: undefined };
}

export const ImportDataRes: MessageFns<ImportDataRes> = {
  encode(message: ImportDataRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ImportDataRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseImportDataRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ImportDataRes {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "",
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: ImportDataRes): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ImportDataRes>, I>>(base?: I): ImportDataRes {
    return ImportDataRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ImportDataRes>, I>>(object: I): ImportDataRes {
    const message = createBaseImportDataRes();
    message.taskId = object.taskId ?? "";
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseDownloadExportReq(): DownloadExportReq {
  return { taskId: "" };
}

export const DownloadExportReq: MessageFns<DownloadExportReq> = {
  encode(message: DownloadExportReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DownloadExportReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDownloadExportReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DownloadExportReq {
    return { taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "" };
  },

  toJSON(message: DownloadExportReq): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DownloadExportReq>, I>>(base?: I): DownloadExportReq {
    return DownloadExportReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DownloadExportReq>, I>>(object: I): DownloadExportReq {
    const message = createBaseDownloadExportReq();
    message.taskId = object.taskId ?? "";
    return message;
  },
};

function createBaseDownloadExportRes(): DownloadExportRes {
  return { fileContent: new Uint8Array(0) };
}

export const DownloadExportRes: MessageFns<DownloadExportRes> = {
  encode(message: DownloadExportRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fileContent.length !== 0) {
      writer.uint32(10).bytes(message.fileContent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DownloadExportRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDownloadExportRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fileContent = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DownloadExportRes {
    return { fileContent: isSet(object.fileContent) ? bytesFromBase64(object.fileContent) : new Uint8Array(0) };
  },

  toJSON(message: DownloadExportRes): unknown {
    const obj: any = {};
    if (message.fileContent.length !== 0) {
      obj.fileContent = base64FromBytes(message.fileContent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DownloadExportRes>, I>>(base?: I): DownloadExportRes {
    return DownloadExportRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DownloadExportRes>, I>>(object: I): DownloadExportRes {
    const message = createBaseDownloadExportRes();
    message.fileContent = object.fileContent ?? new Uint8Array(0);
    return message;
  },
};

function createBaseGetExportStatusReq(): GetExportStatusReq {
  return { taskId: "" };
}

export const GetExportStatusReq: MessageFns<GetExportStatusReq> = {
  encode(message: GetExportStatusReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetExportStatusReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetExportStatusReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetExportStatusReq {
    return { taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "" };
  },

  toJSON(message: GetExportStatusReq): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetExportStatusReq>, I>>(base?: I): GetExportStatusReq {
    return GetExportStatusReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetExportStatusReq>, I>>(object: I): GetExportStatusReq {
    const message = createBaseGetExportStatusReq();
    message.taskId = object.taskId ?? "";
    return message;
  },
};

function createBaseGetExportStatusRes(): GetExportStatusRes {
  return { task: undefined, base: undefined };
}

export const GetExportStatusRes: MessageFns<GetExportStatusRes> = {
  encode(message: GetExportStatusRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.task !== undefined) {
      Task.encode(message.task, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetExportStatusRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetExportStatusRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.task = Task.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetExportStatusRes {
    return {
      task: isSet(object.task) ? Task.fromJSON(object.task) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetExportStatusRes): unknown {
    const obj: any = {};
    if (message.task !== undefined) {
      obj.task = Task.toJSON(message.task);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetExportStatusRes>, I>>(base?: I): GetExportStatusRes {
    return GetExportStatusRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetExportStatusRes>, I>>(object: I): GetExportStatusRes {
    const message = createBaseGetExportStatusRes();
    message.task = (object.task !== undefined && object.task !== null) ? Task.fromPartial(object.task) : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

export interface DataService {
  /** Create data export task */
  ExportData(request: ExportDataReq): Promise<ExportDataRes>;
  /** Create data import task */
  ImportData(request: ImportDataReq): Promise<ImportDataRes>;
  /**
   * Download export file
   * Note: Streaming RPC might be better for large files, but keeping simple for request/response migration
   */
  DownloadExport(request: DownloadExportReq): Promise<DownloadExportRes>;
  /** Get export task status */
  GetExportStatus(request: GetExportStatusReq): Promise<GetExportStatusRes>;
}

export const DataServiceServiceName = "data.v1.DataService";
export class DataServiceClientImpl implements DataService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || DataServiceServiceName;
    this.rpc = rpc;
    this.ExportData = this.ExportData.bind(this);
    this.ImportData = this.ImportData.bind(this);
    this.DownloadExport = this.DownloadExport.bind(this);
    this.GetExportStatus = this.GetExportStatus.bind(this);
  }
  ExportData(request: ExportDataReq): Promise<ExportDataRes> {
    const data = ExportDataReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "ExportData", data);
    return promise.then((data) => ExportDataRes.decode(new BinaryReader(data)));
  }

  ImportData(request: ImportDataReq): Promise<ImportDataRes> {
    const data = ImportDataReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "ImportData", data);
    return promise.then((data) => ImportDataRes.decode(new BinaryReader(data)));
  }

  DownloadExport(request: DownloadExportReq): Promise<DownloadExportRes> {
    const data = DownloadExportReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "DownloadExport", data);
    return promise.then((data) => DownloadExportRes.decode(new BinaryReader(data)));
  }

  GetExportStatus(request: GetExportStatusReq): Promise<GetExportStatusRes> {
    const data = GetExportStatusReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetExportStatus", data);
    return promise.then((data) => GetExportStatusRes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
