// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: transaction/v1/transaction.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  BaseResponse,
  Money,
  PaginatedResponse,
  TransactionType,
  transactionTypeFromJSON,
  transactionTypeToJSON,
} from "../../base/base";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "transaction.v1";

export interface Transaction {
  id: string;
  /** ISO 8601 Date string */
  date: string;
  from: string;
  to: string;
  /** Replaced float64 with Money */
  amount: Money | undefined;
  note: string;
  /** Type: INCOME, EXPENSE, TRANSFER */
  type: TransactionType;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface TransactionInput {
  date: string;
  from: string;
  to: string;
  /** Replaced float64 with Money */
  amount: Money | undefined;
  note: string;
  type: TransactionType;
}

export interface TransactionQuery {
  page: number;
  limit: number;
  startDate: string;
  endDate: string;
  accountId: string;
  type: TransactionType;
  sortBy: string;
  sortOrder: string;
}

export interface ListTransactionsReq {
  query: TransactionQuery | undefined;
}

export interface ListTransactionsRes {
  data: Transaction[];
  pagination: PaginatedResponse | undefined;
  base: BaseResponse | undefined;
}

export interface CreateTransactionReq {
  input: TransactionInput | undefined;
}

export interface CreateTransactionRes {
  transaction: Transaction | undefined;
  base: BaseResponse | undefined;
}

export interface GetTransactionReq {
  id: string;
}

export interface GetTransactionRes {
  transaction: Transaction | undefined;
  base: BaseResponse | undefined;
}

export interface UpdateTransactionReq {
  id: string;
  input: TransactionInput | undefined;
}

export interface UpdateTransactionRes {
  transaction: Transaction | undefined;
  base: BaseResponse | undefined;
}

export interface DeleteTransactionReq {
  id: string;
}

export interface DeleteTransactionRes {
  base: BaseResponse | undefined;
}

function createBaseTransaction(): Transaction {
  return {
    id: "",
    date: "",
    from: "",
    to: "",
    amount: undefined,
    note: "",
    type: 0,
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const Transaction: MessageFns<Transaction> = {
  encode(message: Transaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.date !== "") {
      writer.uint32(18).string(message.date);
    }
    if (message.from !== "") {
      writer.uint32(26).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(34).string(message.to);
    }
    if (message.amount !== undefined) {
      Money.encode(message.amount, writer.uint32(42).fork()).join();
    }
    if (message.note !== "") {
      writer.uint32(50).string(message.note);
    }
    if (message.type !== 0) {
      writer.uint32(56).int32(message.type);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(66).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.amount = Money.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.note = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Transaction {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      amount: isSet(object.amount) ? Money.fromJSON(object.amount) : undefined,
      note: isSet(object.note) ? globalThis.String(object.note) : "",
      type: isSet(object.type) ? transactionTypeFromJSON(object.type) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: Transaction): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.amount !== undefined) {
      obj.amount = Money.toJSON(message.amount);
    }
    if (message.note !== "") {
      obj.note = message.note;
    }
    if (message.type !== 0) {
      obj.type = transactionTypeToJSON(message.type);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Transaction>, I>>(base?: I): Transaction {
    return Transaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Transaction>, I>>(object: I): Transaction {
    const message = createBaseTransaction();
    message.id = object.id ?? "";
    message.date = object.date ?? "";
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.amount = (object.amount !== undefined && object.amount !== null)
      ? Money.fromPartial(object.amount)
      : undefined;
    message.note = object.note ?? "";
    message.type = object.type ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseTransactionInput(): TransactionInput {
  return { date: "", from: "", to: "", amount: undefined, note: "", type: 0 };
}

export const TransactionInput: MessageFns<TransactionInput> = {
  encode(message: TransactionInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    if (message.from !== "") {
      writer.uint32(18).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(26).string(message.to);
    }
    if (message.amount !== undefined) {
      Money.encode(message.amount, writer.uint32(34).fork()).join();
    }
    if (message.note !== "") {
      writer.uint32(42).string(message.note);
    }
    if (message.type !== 0) {
      writer.uint32(48).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = Money.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.note = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionInput {
    return {
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      amount: isSet(object.amount) ? Money.fromJSON(object.amount) : undefined,
      note: isSet(object.note) ? globalThis.String(object.note) : "",
      type: isSet(object.type) ? transactionTypeFromJSON(object.type) : 0,
    };
  },

  toJSON(message: TransactionInput): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.amount !== undefined) {
      obj.amount = Money.toJSON(message.amount);
    }
    if (message.note !== "") {
      obj.note = message.note;
    }
    if (message.type !== 0) {
      obj.type = transactionTypeToJSON(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionInput>, I>>(base?: I): TransactionInput {
    return TransactionInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionInput>, I>>(object: I): TransactionInput {
    const message = createBaseTransactionInput();
    message.date = object.date ?? "";
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.amount = (object.amount !== undefined && object.amount !== null)
      ? Money.fromPartial(object.amount)
      : undefined;
    message.note = object.note ?? "";
    message.type = object.type ?? 0;
    return message;
  },
};

function createBaseTransactionQuery(): TransactionQuery {
  return { page: 0, limit: 0, startDate: "", endDate: "", accountId: "", type: 0, sortBy: "", sortOrder: "" };
}

export const TransactionQuery: MessageFns<TransactionQuery> = {
  encode(message: TransactionQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.startDate !== "") {
      writer.uint32(26).string(message.startDate);
    }
    if (message.endDate !== "") {
      writer.uint32(34).string(message.endDate);
    }
    if (message.accountId !== "") {
      writer.uint32(42).string(message.accountId);
    }
    if (message.type !== 0) {
      writer.uint32(48).int32(message.type);
    }
    if (message.sortBy !== "") {
      writer.uint32(58).string(message.sortBy);
    }
    if (message.sortOrder !== "") {
      writer.uint32(66).string(message.sortOrder);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.startDate = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.endDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sortBy = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.sortOrder = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionQuery {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      startDate: isSet(object.startDate) ? globalThis.String(object.startDate) : "",
      endDate: isSet(object.endDate) ? globalThis.String(object.endDate) : "",
      accountId: isSet(object.accountId) ? globalThis.String(object.accountId) : "",
      type: isSet(object.type) ? transactionTypeFromJSON(object.type) : 0,
      sortBy: isSet(object.sortBy) ? globalThis.String(object.sortBy) : "",
      sortOrder: isSet(object.sortOrder) ? globalThis.String(object.sortOrder) : "",
    };
  },

  toJSON(message: TransactionQuery): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.startDate !== "") {
      obj.startDate = message.startDate;
    }
    if (message.endDate !== "") {
      obj.endDate = message.endDate;
    }
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.type !== 0) {
      obj.type = transactionTypeToJSON(message.type);
    }
    if (message.sortBy !== "") {
      obj.sortBy = message.sortBy;
    }
    if (message.sortOrder !== "") {
      obj.sortOrder = message.sortOrder;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionQuery>, I>>(base?: I): TransactionQuery {
    return TransactionQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionQuery>, I>>(object: I): TransactionQuery {
    const message = createBaseTransactionQuery();
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.startDate = object.startDate ?? "";
    message.endDate = object.endDate ?? "";
    message.accountId = object.accountId ?? "";
    message.type = object.type ?? 0;
    message.sortBy = object.sortBy ?? "";
    message.sortOrder = object.sortOrder ?? "";
    return message;
  },
};

function createBaseListTransactionsReq(): ListTransactionsReq {
  return { query: undefined };
}

export const ListTransactionsReq: MessageFns<ListTransactionsReq> = {
  encode(message: ListTransactionsReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== undefined) {
      TransactionQuery.encode(message.query, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTransactionsReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTransactionsReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = TransactionQuery.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTransactionsReq {
    return { query: isSet(object.query) ? TransactionQuery.fromJSON(object.query) : undefined };
  },

  toJSON(message: ListTransactionsReq): unknown {
    const obj: any = {};
    if (message.query !== undefined) {
      obj.query = TransactionQuery.toJSON(message.query);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTransactionsReq>, I>>(base?: I): ListTransactionsReq {
    return ListTransactionsReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTransactionsReq>, I>>(object: I): ListTransactionsReq {
    const message = createBaseListTransactionsReq();
    message.query = (object.query !== undefined && object.query !== null)
      ? TransactionQuery.fromPartial(object.query)
      : undefined;
    return message;
  },
};

function createBaseListTransactionsRes(): ListTransactionsRes {
  return { data: [], pagination: undefined, base: undefined };
}

export const ListTransactionsRes: MessageFns<ListTransactionsRes> = {
  encode(message: ListTransactionsRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      Transaction.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PaginatedResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTransactionsRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTransactionsRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(Transaction.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PaginatedResponse.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTransactionsRes {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => Transaction.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PaginatedResponse.fromJSON(object.pagination) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: ListTransactionsRes): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => Transaction.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PaginatedResponse.toJSON(message.pagination);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTransactionsRes>, I>>(base?: I): ListTransactionsRes {
    return ListTransactionsRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTransactionsRes>, I>>(object: I): ListTransactionsRes {
    const message = createBaseListTransactionsRes();
    message.data = object.data?.map((e) => Transaction.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginatedResponse.fromPartial(object.pagination)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseCreateTransactionReq(): CreateTransactionReq {
  return { input: undefined };
}

export const CreateTransactionReq: MessageFns<CreateTransactionReq> = {
  encode(message: CreateTransactionReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.input !== undefined) {
      TransactionInput.encode(message.input, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTransactionReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTransactionReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.input = TransactionInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTransactionReq {
    return { input: isSet(object.input) ? TransactionInput.fromJSON(object.input) : undefined };
  },

  toJSON(message: CreateTransactionReq): unknown {
    const obj: any = {};
    if (message.input !== undefined) {
      obj.input = TransactionInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTransactionReq>, I>>(base?: I): CreateTransactionReq {
    return CreateTransactionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTransactionReq>, I>>(object: I): CreateTransactionReq {
    const message = createBaseCreateTransactionReq();
    message.input = (object.input !== undefined && object.input !== null)
      ? TransactionInput.fromPartial(object.input)
      : undefined;
    return message;
  },
};

function createBaseCreateTransactionRes(): CreateTransactionRes {
  return { transaction: undefined, base: undefined };
}

export const CreateTransactionRes: MessageFns<CreateTransactionRes> = {
  encode(message: CreateTransactionRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transaction !== undefined) {
      Transaction.encode(message.transaction, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTransactionRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTransactionRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transaction = Transaction.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTransactionRes {
    return {
      transaction: isSet(object.transaction) ? Transaction.fromJSON(object.transaction) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: CreateTransactionRes): unknown {
    const obj: any = {};
    if (message.transaction !== undefined) {
      obj.transaction = Transaction.toJSON(message.transaction);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTransactionRes>, I>>(base?: I): CreateTransactionRes {
    return CreateTransactionRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTransactionRes>, I>>(object: I): CreateTransactionRes {
    const message = createBaseCreateTransactionRes();
    message.transaction = (object.transaction !== undefined && object.transaction !== null)
      ? Transaction.fromPartial(object.transaction)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetTransactionReq(): GetTransactionReq {
  return { id: "" };
}

export const GetTransactionReq: MessageFns<GetTransactionReq> = {
  encode(message: GetTransactionReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTransactionReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTransactionReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTransactionReq {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetTransactionReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTransactionReq>, I>>(base?: I): GetTransactionReq {
    return GetTransactionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTransactionReq>, I>>(object: I): GetTransactionReq {
    const message = createBaseGetTransactionReq();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetTransactionRes(): GetTransactionRes {
  return { transaction: undefined, base: undefined };
}

export const GetTransactionRes: MessageFns<GetTransactionRes> = {
  encode(message: GetTransactionRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transaction !== undefined) {
      Transaction.encode(message.transaction, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTransactionRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTransactionRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transaction = Transaction.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTransactionRes {
    return {
      transaction: isSet(object.transaction) ? Transaction.fromJSON(object.transaction) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetTransactionRes): unknown {
    const obj: any = {};
    if (message.transaction !== undefined) {
      obj.transaction = Transaction.toJSON(message.transaction);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTransactionRes>, I>>(base?: I): GetTransactionRes {
    return GetTransactionRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTransactionRes>, I>>(object: I): GetTransactionRes {
    const message = createBaseGetTransactionRes();
    message.transaction = (object.transaction !== undefined && object.transaction !== null)
      ? Transaction.fromPartial(object.transaction)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseUpdateTransactionReq(): UpdateTransactionReq {
  return { id: "", input: undefined };
}

export const UpdateTransactionReq: MessageFns<UpdateTransactionReq> = {
  encode(message: UpdateTransactionReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.input !== undefined) {
      TransactionInput.encode(message.input, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTransactionReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTransactionReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = TransactionInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTransactionReq {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      input: isSet(object.input) ? TransactionInput.fromJSON(object.input) : undefined,
    };
  },

  toJSON(message: UpdateTransactionReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.input !== undefined) {
      obj.input = TransactionInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTransactionReq>, I>>(base?: I): UpdateTransactionReq {
    return UpdateTransactionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTransactionReq>, I>>(object: I): UpdateTransactionReq {
    const message = createBaseUpdateTransactionReq();
    message.id = object.id ?? "";
    message.input = (object.input !== undefined && object.input !== null)
      ? TransactionInput.fromPartial(object.input)
      : undefined;
    return message;
  },
};

function createBaseUpdateTransactionRes(): UpdateTransactionRes {
  return { transaction: undefined, base: undefined };
}

export const UpdateTransactionRes: MessageFns<UpdateTransactionRes> = {
  encode(message: UpdateTransactionRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transaction !== undefined) {
      Transaction.encode(message.transaction, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTransactionRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTransactionRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transaction = Transaction.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTransactionRes {
    return {
      transaction: isSet(object.transaction) ? Transaction.fromJSON(object.transaction) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: UpdateTransactionRes): unknown {
    const obj: any = {};
    if (message.transaction !== undefined) {
      obj.transaction = Transaction.toJSON(message.transaction);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTransactionRes>, I>>(base?: I): UpdateTransactionRes {
    return UpdateTransactionRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTransactionRes>, I>>(object: I): UpdateTransactionRes {
    const message = createBaseUpdateTransactionRes();
    message.transaction = (object.transaction !== undefined && object.transaction !== null)
      ? Transaction.fromPartial(object.transaction)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseDeleteTransactionReq(): DeleteTransactionReq {
  return { id: "" };
}

export const DeleteTransactionReq: MessageFns<DeleteTransactionReq> = {
  encode(message: DeleteTransactionReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTransactionReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTransactionReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTransactionReq {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteTransactionReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTransactionReq>, I>>(base?: I): DeleteTransactionReq {
    return DeleteTransactionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTransactionReq>, I>>(object: I): DeleteTransactionReq {
    const message = createBaseDeleteTransactionReq();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDeleteTransactionRes(): DeleteTransactionRes {
  return { base: undefined };
}

export const DeleteTransactionRes: MessageFns<DeleteTransactionRes> = {
  encode(message: DeleteTransactionRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTransactionRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTransactionRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTransactionRes {
    return { base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined };
  },

  toJSON(message: DeleteTransactionRes): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTransactionRes>, I>>(base?: I): DeleteTransactionRes {
    return DeleteTransactionRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTransactionRes>, I>>(object: I): DeleteTransactionRes {
    const message = createBaseDeleteTransactionRes();
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

export interface TransactionService {
  /** List transactions */
  ListTransactions(request: ListTransactionsReq): Promise<ListTransactionsRes>;
  /** Create a new transaction */
  CreateTransaction(request: CreateTransactionReq): Promise<CreateTransactionRes>;
  /** Get transaction details */
  GetTransaction(request: GetTransactionReq): Promise<GetTransactionRes>;
  /** Update transaction */
  UpdateTransaction(request: UpdateTransactionReq): Promise<UpdateTransactionRes>;
  /** Delete transaction */
  DeleteTransaction(request: DeleteTransactionReq): Promise<DeleteTransactionRes>;
}

export const TransactionServiceServiceName = "transaction.v1.TransactionService";
export class TransactionServiceClientImpl implements TransactionService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TransactionServiceServiceName;
    this.rpc = rpc;
    this.ListTransactions = this.ListTransactions.bind(this);
    this.CreateTransaction = this.CreateTransaction.bind(this);
    this.GetTransaction = this.GetTransaction.bind(this);
    this.UpdateTransaction = this.UpdateTransaction.bind(this);
    this.DeleteTransaction = this.DeleteTransaction.bind(this);
  }
  ListTransactions(request: ListTransactionsReq): Promise<ListTransactionsRes> {
    const data = ListTransactionsReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListTransactions", data);
    return promise.then((data) => ListTransactionsRes.decode(new BinaryReader(data)));
  }

  CreateTransaction(request: CreateTransactionReq): Promise<CreateTransactionRes> {
    const data = CreateTransactionReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateTransaction", data);
    return promise.then((data) => CreateTransactionRes.decode(new BinaryReader(data)));
  }

  GetTransaction(request: GetTransactionReq): Promise<GetTransactionRes> {
    const data = GetTransactionReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTransaction", data);
    return promise.then((data) => GetTransactionRes.decode(new BinaryReader(data)));
  }

  UpdateTransaction(request: UpdateTransactionReq): Promise<UpdateTransactionRes> {
    const data = UpdateTransactionReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateTransaction", data);
    return promise.then((data) => UpdateTransactionRes.decode(new BinaryReader(data)));
  }

  DeleteTransaction(request: DeleteTransactionReq): Promise<DeleteTransactionRes> {
    const data = DeleteTransactionReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteTransaction", data);
    return promise.then((data) => DeleteTransactionRes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
