// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: account/v1/account.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  AccountType,
  accountTypeFromJSON,
  accountTypeToJSON,
  BaseResponse,
  Money,
  PaginatedResponse,
} from "../../base/base";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "account.v1";

export interface Account {
  id: string;
  parentId?: string | undefined;
  name: string;
  type: AccountType;
  isGroup: boolean;
  /** Replaced float64 with Money */
  balance: Money | undefined;
  defaultChildId?:
  | string
  | undefined;
  /** ISO 8601 Date string */
  date: string;
  number: string;
  remarks: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
  openingVoucherId: string;
}

export interface AccountInput {
  parentId?: string | undefined;
  name: string;
  type: AccountType;
  isGroup: boolean;
  /** Replaced float64 with Money */
  balance: Money | undefined;
  defaultChildId?: string | undefined;
  date: string;
  number?: string | undefined;
  remarks?: string | undefined;
}

export interface AccountQuery {
  page: number;
  limit: number;
  type: AccountType;
  parentId: string;
}

export interface ListAccountsReq {
  query: AccountQuery | undefined;
}

export interface ListAccountsRes {
  data: Account[];
  pagination: PaginatedResponse | undefined;
  base: BaseResponse | undefined;
}

export interface CreateAccountReq {
  input: AccountInput | undefined;
}

export interface CreateAccountRes {
  account: Account | undefined;
  base: BaseResponse | undefined;
}

export interface GetAccountReq {
  id: string;
}

export interface GetAccountRes {
  account: Account | undefined;
  base: BaseResponse | undefined;
}

export interface UpdateAccountReq {
  id: string;
  input: AccountInput | undefined;
}

export interface UpdateAccountRes {
  account: Account | undefined;
  base: BaseResponse | undefined;
}

export interface DeleteAccountReq {
  id: string;
  /** map<currency, targetAccountId> */
  migrationTargets: { [key: string]: string };
}

export interface DeleteAccountReq_MigrationTargetsEntry {
  key: string;
  value: string;
}

export interface DeleteAccountRes {
  taskId: string;
  base: BaseResponse | undefined;
}

export interface GetAccountTransactionCountReq {
  id: string;
}

export interface GetAccountTransactionCountRes {
  count: number;
  base: BaseResponse | undefined;
}

function createBaseAccount(): Account {
  return {
    id: "",
    parentId: undefined,
    name: "",
    type: 0,
    isGroup: false,
    balance: undefined,
    defaultChildId: undefined,
    date: "",
    number: "",
    remarks: "",
    createdAt: undefined,
    updatedAt: undefined,
    openingVoucherId: "",
  };
}

export const Account: MessageFns<Account> = {
  encode(message: Account, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.parentId !== undefined) {
      writer.uint32(18).string(message.parentId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    if (message.isGroup !== false) {
      writer.uint32(40).bool(message.isGroup);
    }
    if (message.balance !== undefined) {
      Money.encode(message.balance, writer.uint32(50).fork()).join();
    }
    if (message.defaultChildId !== undefined) {
      writer.uint32(58).string(message.defaultChildId);
    }
    if (message.date !== "") {
      writer.uint32(66).string(message.date);
    }
    if (message.number !== "") {
      writer.uint32(74).string(message.number);
    }
    if (message.remarks !== "") {
      writer.uint32(82).string(message.remarks);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(90).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(98).fork()).join();
    }
    if (message.openingVoucherId !== "") {
      writer.uint32(106).string(message.openingVoucherId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Account {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isGroup = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.balance = Money.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.defaultChildId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.number = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.remarks = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.openingVoucherId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Account {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      parentId: isSet(object.parentId) ? globalThis.String(object.parentId) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? accountTypeFromJSON(object.type) : 0,
      isGroup: isSet(object.isGroup) ? globalThis.Boolean(object.isGroup) : false,
      balance: isSet(object.balance) ? Money.fromJSON(object.balance) : undefined,
      defaultChildId: isSet(object.defaultChildId) ? globalThis.String(object.defaultChildId) : undefined,
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      number: isSet(object.number) ? globalThis.String(object.number) : "",
      remarks: isSet(object.remarks) ? globalThis.String(object.remarks) : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
      openingVoucherId: isSet(object.openingVoucherId) ? globalThis.String(object.openingVoucherId) : "",
    };
  },

  toJSON(message: Account): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.parentId !== undefined) {
      obj.parentId = message.parentId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== 0) {
      obj.type = accountTypeToJSON(message.type);
    }
    if (message.isGroup !== false) {
      obj.isGroup = message.isGroup;
    }
    if (message.balance !== undefined) {
      obj.balance = Money.toJSON(message.balance);
    }
    if (message.defaultChildId !== undefined) {
      obj.defaultChildId = message.defaultChildId;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.number !== "") {
      obj.number = message.number;
    }
    if (message.remarks !== "") {
      obj.remarks = message.remarks;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    if (message.openingVoucherId !== "") {
      obj.openingVoucherId = message.openingVoucherId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Account>, I>>(base?: I): Account {
    return Account.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Account>, I>>(object: I): Account {
    const message = createBaseAccount();
    message.id = object.id ?? "";
    message.parentId = object.parentId ?? undefined;
    message.name = object.name ?? "";
    message.type = object.type ?? 0;
    message.isGroup = object.isGroup ?? false;
    message.balance = (object.balance !== undefined && object.balance !== null)
      ? Money.fromPartial(object.balance)
      : undefined;
    message.defaultChildId = object.defaultChildId ?? undefined;
    message.date = object.date ?? "";
    message.number = object.number ?? "";
    message.remarks = object.remarks ?? "";
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    message.openingVoucherId = object.openingVoucherId ?? "";
    return message;
  },
};

function createBaseAccountInput(): AccountInput {
  return {
    parentId: undefined,
    name: "",
    type: 0,
    isGroup: false,
    balance: undefined,
    defaultChildId: undefined,
    date: "",
    number: undefined,
    remarks: undefined,
  };
}

export const AccountInput: MessageFns<AccountInput> = {
  encode(message: AccountInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parentId !== undefined) {
      writer.uint32(10).string(message.parentId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    if (message.isGroup !== false) {
      writer.uint32(32).bool(message.isGroup);
    }
    if (message.balance !== undefined) {
      Money.encode(message.balance, writer.uint32(42).fork()).join();
    }
    if (message.defaultChildId !== undefined) {
      writer.uint32(50).string(message.defaultChildId);
    }
    if (message.date !== "") {
      writer.uint32(58).string(message.date);
    }
    if (message.number !== undefined) {
      writer.uint32(66).string(message.number);
    }
    if (message.remarks !== undefined) {
      writer.uint32(74).string(message.remarks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isGroup = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.balance = Money.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.defaultChildId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.number = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.remarks = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountInput {
    return {
      parentId: isSet(object.parentId) ? globalThis.String(object.parentId) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? accountTypeFromJSON(object.type) : 0,
      isGroup: isSet(object.isGroup) ? globalThis.Boolean(object.isGroup) : false,
      balance: isSet(object.balance) ? Money.fromJSON(object.balance) : undefined,
      defaultChildId: isSet(object.defaultChildId) ? globalThis.String(object.defaultChildId) : undefined,
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      number: isSet(object.number) ? globalThis.String(object.number) : undefined,
      remarks: isSet(object.remarks) ? globalThis.String(object.remarks) : undefined,
    };
  },

  toJSON(message: AccountInput): unknown {
    const obj: any = {};
    if (message.parentId !== undefined) {
      obj.parentId = message.parentId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== 0) {
      obj.type = accountTypeToJSON(message.type);
    }
    if (message.isGroup !== false) {
      obj.isGroup = message.isGroup;
    }
    if (message.balance !== undefined) {
      obj.balance = Money.toJSON(message.balance);
    }
    if (message.defaultChildId !== undefined) {
      obj.defaultChildId = message.defaultChildId;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.number !== undefined) {
      obj.number = message.number;
    }
    if (message.remarks !== undefined) {
      obj.remarks = message.remarks;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountInput>, I>>(base?: I): AccountInput {
    return AccountInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountInput>, I>>(object: I): AccountInput {
    const message = createBaseAccountInput();
    message.parentId = object.parentId ?? undefined;
    message.name = object.name ?? "";
    message.type = object.type ?? 0;
    message.isGroup = object.isGroup ?? false;
    message.balance = (object.balance !== undefined && object.balance !== null)
      ? Money.fromPartial(object.balance)
      : undefined;
    message.defaultChildId = object.defaultChildId ?? undefined;
    message.date = object.date ?? "";
    message.number = object.number ?? undefined;
    message.remarks = object.remarks ?? undefined;
    return message;
  },
};

function createBaseAccountQuery(): AccountQuery {
  return { page: 0, limit: 0, type: 0, parentId: "" };
}

export const AccountQuery: MessageFns<AccountQuery> = {
  encode(message: AccountQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    if (message.parentId !== "") {
      writer.uint32(34).string(message.parentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountQuery {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      type: isSet(object.type) ? accountTypeFromJSON(object.type) : 0,
      parentId: isSet(object.parentId) ? globalThis.String(object.parentId) : "",
    };
  },

  toJSON(message: AccountQuery): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.type !== 0) {
      obj.type = accountTypeToJSON(message.type);
    }
    if (message.parentId !== "") {
      obj.parentId = message.parentId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountQuery>, I>>(base?: I): AccountQuery {
    return AccountQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountQuery>, I>>(object: I): AccountQuery {
    const message = createBaseAccountQuery();
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.type = object.type ?? 0;
    message.parentId = object.parentId ?? "";
    return message;
  },
};

function createBaseListAccountsReq(): ListAccountsReq {
  return { query: undefined };
}

export const ListAccountsReq: MessageFns<ListAccountsReq> = {
  encode(message: ListAccountsReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== undefined) {
      AccountQuery.encode(message.query, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAccountsReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAccountsReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = AccountQuery.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAccountsReq {
    return { query: isSet(object.query) ? AccountQuery.fromJSON(object.query) : undefined };
  },

  toJSON(message: ListAccountsReq): unknown {
    const obj: any = {};
    if (message.query !== undefined) {
      obj.query = AccountQuery.toJSON(message.query);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAccountsReq>, I>>(base?: I): ListAccountsReq {
    return ListAccountsReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAccountsReq>, I>>(object: I): ListAccountsReq {
    const message = createBaseListAccountsReq();
    message.query = (object.query !== undefined && object.query !== null)
      ? AccountQuery.fromPartial(object.query)
      : undefined;
    return message;
  },
};

function createBaseListAccountsRes(): ListAccountsRes {
  return { data: [], pagination: undefined, base: undefined };
}

export const ListAccountsRes: MessageFns<ListAccountsRes> = {
  encode(message: ListAccountsRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      Account.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PaginatedResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAccountsRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAccountsRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(Account.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PaginatedResponse.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAccountsRes {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => Account.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PaginatedResponse.fromJSON(object.pagination) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: ListAccountsRes): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => Account.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PaginatedResponse.toJSON(message.pagination);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAccountsRes>, I>>(base?: I): ListAccountsRes {
    return ListAccountsRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAccountsRes>, I>>(object: I): ListAccountsRes {
    const message = createBaseListAccountsRes();
    message.data = object.data?.map((e) => Account.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginatedResponse.fromPartial(object.pagination)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseCreateAccountReq(): CreateAccountReq {
  return { input: undefined };
}

export const CreateAccountReq: MessageFns<CreateAccountReq> = {
  encode(message: CreateAccountReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.input !== undefined) {
      AccountInput.encode(message.input, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAccountReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAccountReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.input = AccountInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateAccountReq {
    return { input: isSet(object.input) ? AccountInput.fromJSON(object.input) : undefined };
  },

  toJSON(message: CreateAccountReq): unknown {
    const obj: any = {};
    if (message.input !== undefined) {
      obj.input = AccountInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateAccountReq>, I>>(base?: I): CreateAccountReq {
    return CreateAccountReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateAccountReq>, I>>(object: I): CreateAccountReq {
    const message = createBaseCreateAccountReq();
    message.input = (object.input !== undefined && object.input !== null)
      ? AccountInput.fromPartial(object.input)
      : undefined;
    return message;
  },
};

function createBaseCreateAccountRes(): CreateAccountRes {
  return { account: undefined, base: undefined };
}

export const CreateAccountRes: MessageFns<CreateAccountRes> = {
  encode(message: CreateAccountRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account !== undefined) {
      Account.encode(message.account, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAccountRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAccountRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.account = Account.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateAccountRes {
    return {
      account: isSet(object.account) ? Account.fromJSON(object.account) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: CreateAccountRes): unknown {
    const obj: any = {};
    if (message.account !== undefined) {
      obj.account = Account.toJSON(message.account);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateAccountRes>, I>>(base?: I): CreateAccountRes {
    return CreateAccountRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateAccountRes>, I>>(object: I): CreateAccountRes {
    const message = createBaseCreateAccountRes();
    message.account = (object.account !== undefined && object.account !== null)
      ? Account.fromPartial(object.account)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetAccountReq(): GetAccountReq {
  return { id: "" };
}

export const GetAccountReq: MessageFns<GetAccountReq> = {
  encode(message: GetAccountReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccountReq {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetAccountReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountReq>, I>>(base?: I): GetAccountReq {
    return GetAccountReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountReq>, I>>(object: I): GetAccountReq {
    const message = createBaseGetAccountReq();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetAccountRes(): GetAccountRes {
  return { account: undefined, base: undefined };
}

export const GetAccountRes: MessageFns<GetAccountRes> = {
  encode(message: GetAccountRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account !== undefined) {
      Account.encode(message.account, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.account = Account.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccountRes {
    return {
      account: isSet(object.account) ? Account.fromJSON(object.account) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetAccountRes): unknown {
    const obj: any = {};
    if (message.account !== undefined) {
      obj.account = Account.toJSON(message.account);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountRes>, I>>(base?: I): GetAccountRes {
    return GetAccountRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountRes>, I>>(object: I): GetAccountRes {
    const message = createBaseGetAccountRes();
    message.account = (object.account !== undefined && object.account !== null)
      ? Account.fromPartial(object.account)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseUpdateAccountReq(): UpdateAccountReq {
  return { id: "", input: undefined };
}

export const UpdateAccountReq: MessageFns<UpdateAccountReq> = {
  encode(message: UpdateAccountReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.input !== undefined) {
      AccountInput.encode(message.input, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateAccountReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateAccountReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = AccountInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateAccountReq {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      input: isSet(object.input) ? AccountInput.fromJSON(object.input) : undefined,
    };
  },

  toJSON(message: UpdateAccountReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.input !== undefined) {
      obj.input = AccountInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateAccountReq>, I>>(base?: I): UpdateAccountReq {
    return UpdateAccountReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateAccountReq>, I>>(object: I): UpdateAccountReq {
    const message = createBaseUpdateAccountReq();
    message.id = object.id ?? "";
    message.input = (object.input !== undefined && object.input !== null)
      ? AccountInput.fromPartial(object.input)
      : undefined;
    return message;
  },
};

function createBaseUpdateAccountRes(): UpdateAccountRes {
  return { account: undefined, base: undefined };
}

export const UpdateAccountRes: MessageFns<UpdateAccountRes> = {
  encode(message: UpdateAccountRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account !== undefined) {
      Account.encode(message.account, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateAccountRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateAccountRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.account = Account.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateAccountRes {
    return {
      account: isSet(object.account) ? Account.fromJSON(object.account) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: UpdateAccountRes): unknown {
    const obj: any = {};
    if (message.account !== undefined) {
      obj.account = Account.toJSON(message.account);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateAccountRes>, I>>(base?: I): UpdateAccountRes {
    return UpdateAccountRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateAccountRes>, I>>(object: I): UpdateAccountRes {
    const message = createBaseUpdateAccountRes();
    message.account = (object.account !== undefined && object.account !== null)
      ? Account.fromPartial(object.account)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseDeleteAccountReq(): DeleteAccountReq {
  return { id: "", migrationTargets: {} };
}

export const DeleteAccountReq: MessageFns<DeleteAccountReq> = {
  encode(message: DeleteAccountReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    globalThis.Object.entries(message.migrationTargets).forEach(([key, value]: [string, string]) => {
      DeleteAccountReq_MigrationTargetsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteAccountReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAccountReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = DeleteAccountReq_MigrationTargetsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.migrationTargets[entry2.key] = entry2.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAccountReq {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      migrationTargets: isObject(object.migrationTargets)
        ? (globalThis.Object.entries(object.migrationTargets) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: DeleteAccountReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.migrationTargets) {
      const entries = globalThis.Object.entries(message.migrationTargets) as [string, string][];
      if (entries.length > 0) {
        obj.migrationTargets = {};
        entries.forEach(([k, v]) => {
          obj.migrationTargets[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteAccountReq>, I>>(base?: I): DeleteAccountReq {
    return DeleteAccountReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteAccountReq>, I>>(object: I): DeleteAccountReq {
    const message = createBaseDeleteAccountReq();
    message.id = object.id ?? "";
    message.migrationTargets = (globalThis.Object.entries(object.migrationTargets ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDeleteAccountReq_MigrationTargetsEntry(): DeleteAccountReq_MigrationTargetsEntry {
  return { key: "", value: "" };
}

export const DeleteAccountReq_MigrationTargetsEntry: MessageFns<DeleteAccountReq_MigrationTargetsEntry> = {
  encode(message: DeleteAccountReq_MigrationTargetsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteAccountReq_MigrationTargetsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAccountReq_MigrationTargetsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAccountReq_MigrationTargetsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: DeleteAccountReq_MigrationTargetsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteAccountReq_MigrationTargetsEntry>, I>>(
    base?: I,
  ): DeleteAccountReq_MigrationTargetsEntry {
    return DeleteAccountReq_MigrationTargetsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteAccountReq_MigrationTargetsEntry>, I>>(
    object: I,
  ): DeleteAccountReq_MigrationTargetsEntry {
    const message = createBaseDeleteAccountReq_MigrationTargetsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseDeleteAccountRes(): DeleteAccountRes {
  return { taskId: "", base: undefined };
}

export const DeleteAccountRes: MessageFns<DeleteAccountRes> = {
  encode(message: DeleteAccountRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteAccountRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAccountRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAccountRes {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "",
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: DeleteAccountRes): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteAccountRes>, I>>(base?: I): DeleteAccountRes {
    return DeleteAccountRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteAccountRes>, I>>(object: I): DeleteAccountRes {
    const message = createBaseDeleteAccountRes();
    message.taskId = object.taskId ?? "";
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseGetAccountTransactionCountReq(): GetAccountTransactionCountReq {
  return { id: "" };
}

export const GetAccountTransactionCountReq: MessageFns<GetAccountTransactionCountReq> = {
  encode(message: GetAccountTransactionCountReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountTransactionCountReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountTransactionCountReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccountTransactionCountReq {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetAccountTransactionCountReq): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountTransactionCountReq>, I>>(base?: I): GetAccountTransactionCountReq {
    return GetAccountTransactionCountReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountTransactionCountReq>, I>>(
    object: I,
  ): GetAccountTransactionCountReq {
    const message = createBaseGetAccountTransactionCountReq();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetAccountTransactionCountRes(): GetAccountTransactionCountRes {
  return { count: 0, base: undefined };
}

export const GetAccountTransactionCountRes: MessageFns<GetAccountTransactionCountRes> = {
  encode(message: GetAccountTransactionCountRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.count !== 0) {
      writer.uint32(8).int32(message.count);
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountTransactionCountRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountTransactionCountRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccountTransactionCountRes {
    return {
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetAccountTransactionCountRes): unknown {
    const obj: any = {};
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountTransactionCountRes>, I>>(base?: I): GetAccountTransactionCountRes {
    return GetAccountTransactionCountRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountTransactionCountRes>, I>>(
    object: I,
  ): GetAccountTransactionCountRes {
    const message = createBaseGetAccountTransactionCountRes();
    message.count = object.count ?? 0;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

export interface AccountService {
  /** List all accounts */
  ListAccounts(request: ListAccountsReq): Promise<ListAccountsRes>;
  /** Create a new account */
  CreateAccount(request: CreateAccountReq): Promise<CreateAccountRes>;
  /** Get account details */
  GetAccount(request: GetAccountReq): Promise<GetAccountRes>;
  /** Update account */
  UpdateAccount(request: UpdateAccountReq): Promise<UpdateAccountRes>;
  /** Delete account with optional migration */
  DeleteAccount(request: DeleteAccountReq): Promise<DeleteAccountRes>;
  /** Get transaction count for account */
  GetAccountTransactionCount(request: GetAccountTransactionCountReq): Promise<GetAccountTransactionCountRes>;
}

export const AccountServiceServiceName = "account.v1.AccountService";
export class AccountServiceClientImpl implements AccountService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AccountServiceServiceName;
    this.rpc = rpc;
    this.ListAccounts = this.ListAccounts.bind(this);
    this.CreateAccount = this.CreateAccount.bind(this);
    this.GetAccount = this.GetAccount.bind(this);
    this.UpdateAccount = this.UpdateAccount.bind(this);
    this.DeleteAccount = this.DeleteAccount.bind(this);
    this.GetAccountTransactionCount = this.GetAccountTransactionCount.bind(this);
  }
  ListAccounts(request: ListAccountsReq): Promise<ListAccountsRes> {
    const data = ListAccountsReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListAccounts", data);
    return promise.then((data) => ListAccountsRes.decode(new BinaryReader(data)));
  }

  CreateAccount(request: CreateAccountReq): Promise<CreateAccountRes> {
    const data = CreateAccountReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateAccount", data);
    return promise.then((data) => CreateAccountRes.decode(new BinaryReader(data)));
  }

  GetAccount(request: GetAccountReq): Promise<GetAccountRes> {
    const data = GetAccountReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAccount", data);
    return promise.then((data) => GetAccountRes.decode(new BinaryReader(data)));
  }

  UpdateAccount(request: UpdateAccountReq): Promise<UpdateAccountRes> {
    const data = UpdateAccountReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateAccount", data);
    return promise.then((data) => UpdateAccountRes.decode(new BinaryReader(data)));
  }

  DeleteAccount(request: DeleteAccountReq): Promise<DeleteAccountRes> {
    const data = DeleteAccountReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteAccount", data);
    return promise.then((data) => DeleteAccountRes.decode(new BinaryReader(data)));
  }

  GetAccountTransactionCount(request: GetAccountTransactionCountReq): Promise<GetAccountTransactionCountRes> {
    const data = GetAccountTransactionCountReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAccountTransactionCount", data);
    return promise.then((data) => GetAccountTransactionCountRes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
