// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: user/v1/user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BaseResponse, Theme, UserLevelType, userLevelTypeFromJSON, userLevelTypeToJSON } from "../../base/base";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "user.v1";

/** User data structure */
export interface User {
  id: string;
  email: string;
  nickname: string;
  avatar?:
    | string
    | undefined;
  /** Plan type: FREE, PRO */
  plan: UserLevelType;
  twoFactorEnabled: boolean;
  mainCurrency: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface UserInput {
  nickname: string;
  avatar?: string | undefined;
  plan: UserLevelType;
}

export interface GetUserProfileReq {
}

export interface GetUserProfileRes {
  user: User | undefined;
  base: BaseResponse | undefined;
}

export interface UpdateUserProfileReq {
  input: UserInput | undefined;
}

export interface UpdateUserProfileRes {
  user: User | undefined;
  base: BaseResponse | undefined;
}

export interface UpdateThemePreferenceReq {
  theme: Theme | undefined;
}

export interface UpdateThemePreferenceRes {
  theme: Theme | undefined;
  base: BaseResponse | undefined;
}

function createBaseUser(): User {
  return {
    id: "",
    email: "",
    nickname: "",
    avatar: undefined,
    plan: 0,
    twoFactorEnabled: false,
    mainCurrency: "",
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const User: MessageFns<User> = {
  encode(message: User, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.nickname !== "") {
      writer.uint32(26).string(message.nickname);
    }
    if (message.avatar !== undefined) {
      writer.uint32(34).string(message.avatar);
    }
    if (message.plan !== 0) {
      writer.uint32(40).int32(message.plan);
    }
    if (message.twoFactorEnabled !== false) {
      writer.uint32(48).bool(message.twoFactorEnabled);
    }
    if (message.mainCurrency !== "") {
      writer.uint32(58).string(message.mainCurrency);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(66).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.plan = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.twoFactorEnabled = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.mainCurrency = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : undefined,
      plan: isSet(object.plan) ? userLevelTypeFromJSON(object.plan) : 0,
      twoFactorEnabled: isSet(object.twoFactorEnabled) ? globalThis.Boolean(object.twoFactorEnabled) : false,
      mainCurrency: isSet(object.mainCurrency) ? globalThis.String(object.mainCurrency) : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    if (message.avatar !== undefined) {
      obj.avatar = message.avatar;
    }
    if (message.plan !== 0) {
      obj.plan = userLevelTypeToJSON(message.plan);
    }
    if (message.twoFactorEnabled !== false) {
      obj.twoFactorEnabled = message.twoFactorEnabled;
    }
    if (message.mainCurrency !== "") {
      obj.mainCurrency = message.mainCurrency;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User>, I>>(base?: I): User {
    return User.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User>, I>>(object: I): User {
    const message = createBaseUser();
    message.id = object.id ?? "";
    message.email = object.email ?? "";
    message.nickname = object.nickname ?? "";
    message.avatar = object.avatar ?? undefined;
    message.plan = object.plan ?? 0;
    message.twoFactorEnabled = object.twoFactorEnabled ?? false;
    message.mainCurrency = object.mainCurrency ?? "";
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseUserInput(): UserInput {
  return { nickname: "", avatar: undefined, plan: 0 };
}

export const UserInput: MessageFns<UserInput> = {
  encode(message: UserInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nickname !== "") {
      writer.uint32(10).string(message.nickname);
    }
    if (message.avatar !== undefined) {
      writer.uint32(18).string(message.avatar);
    }
    if (message.plan !== 0) {
      writer.uint32(24).int32(message.plan);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.plan = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserInput {
    return {
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : undefined,
      plan: isSet(object.plan) ? userLevelTypeFromJSON(object.plan) : 0,
    };
  },

  toJSON(message: UserInput): unknown {
    const obj: any = {};
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    if (message.avatar !== undefined) {
      obj.avatar = message.avatar;
    }
    if (message.plan !== 0) {
      obj.plan = userLevelTypeToJSON(message.plan);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserInput>, I>>(base?: I): UserInput {
    return UserInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserInput>, I>>(object: I): UserInput {
    const message = createBaseUserInput();
    message.nickname = object.nickname ?? "";
    message.avatar = object.avatar ?? undefined;
    message.plan = object.plan ?? 0;
    return message;
  },
};

function createBaseGetUserProfileReq(): GetUserProfileReq {
  return {};
}

export const GetUserProfileReq: MessageFns<GetUserProfileReq> = {
  encode(_: GetUserProfileReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserProfileReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserProfileReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetUserProfileReq {
    return {};
  },

  toJSON(_: GetUserProfileReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserProfileReq>, I>>(base?: I): GetUserProfileReq {
    return GetUserProfileReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserProfileReq>, I>>(_: I): GetUserProfileReq {
    const message = createBaseGetUserProfileReq();
    return message;
  },
};

function createBaseGetUserProfileRes(): GetUserProfileRes {
  return { user: undefined, base: undefined };
}

export const GetUserProfileRes: MessageFns<GetUserProfileRes> = {
  encode(message: GetUserProfileRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserProfileRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserProfileRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserProfileRes {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: GetUserProfileRes): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserProfileRes>, I>>(base?: I): GetUserProfileRes {
    return GetUserProfileRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserProfileRes>, I>>(object: I): GetUserProfileRes {
    const message = createBaseGetUserProfileRes();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseUpdateUserProfileReq(): UpdateUserProfileReq {
  return { input: undefined };
}

export const UpdateUserProfileReq: MessageFns<UpdateUserProfileReq> = {
  encode(message: UpdateUserProfileReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.input !== undefined) {
      UserInput.encode(message.input, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserProfileReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserProfileReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.input = UserInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserProfileReq {
    return { input: isSet(object.input) ? UserInput.fromJSON(object.input) : undefined };
  },

  toJSON(message: UpdateUserProfileReq): unknown {
    const obj: any = {};
    if (message.input !== undefined) {
      obj.input = UserInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserProfileReq>, I>>(base?: I): UpdateUserProfileReq {
    return UpdateUserProfileReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserProfileReq>, I>>(object: I): UpdateUserProfileReq {
    const message = createBaseUpdateUserProfileReq();
    message.input = (object.input !== undefined && object.input !== null)
      ? UserInput.fromPartial(object.input)
      : undefined;
    return message;
  },
};

function createBaseUpdateUserProfileRes(): UpdateUserProfileRes {
  return { user: undefined, base: undefined };
}

export const UpdateUserProfileRes: MessageFns<UpdateUserProfileRes> = {
  encode(message: UpdateUserProfileRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserProfileRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserProfileRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserProfileRes {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: UpdateUserProfileRes): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserProfileRes>, I>>(base?: I): UpdateUserProfileRes {
    return UpdateUserProfileRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserProfileRes>, I>>(object: I): UpdateUserProfileRes {
    const message = createBaseUpdateUserProfileRes();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function createBaseUpdateThemePreferenceReq(): UpdateThemePreferenceReq {
  return { theme: undefined };
}

export const UpdateThemePreferenceReq: MessageFns<UpdateThemePreferenceReq> = {
  encode(message: UpdateThemePreferenceReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.theme !== undefined) {
      Theme.encode(message.theme, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateThemePreferenceReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateThemePreferenceReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.theme = Theme.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateThemePreferenceReq {
    return { theme: isSet(object.theme) ? Theme.fromJSON(object.theme) : undefined };
  },

  toJSON(message: UpdateThemePreferenceReq): unknown {
    const obj: any = {};
    if (message.theme !== undefined) {
      obj.theme = Theme.toJSON(message.theme);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateThemePreferenceReq>, I>>(base?: I): UpdateThemePreferenceReq {
    return UpdateThemePreferenceReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateThemePreferenceReq>, I>>(object: I): UpdateThemePreferenceReq {
    const message = createBaseUpdateThemePreferenceReq();
    message.theme = (object.theme !== undefined && object.theme !== null) ? Theme.fromPartial(object.theme) : undefined;
    return message;
  },
};

function createBaseUpdateThemePreferenceRes(): UpdateThemePreferenceRes {
  return { theme: undefined, base: undefined };
}

export const UpdateThemePreferenceRes: MessageFns<UpdateThemePreferenceRes> = {
  encode(message: UpdateThemePreferenceRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.theme !== undefined) {
      Theme.encode(message.theme, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseResponse.encode(message.base, writer.uint32(2042).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateThemePreferenceRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateThemePreferenceRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.theme = Theme.decode(reader, reader.uint32());
          continue;
        }
        case 255: {
          if (tag !== 2042) {
            break;
          }

          message.base = BaseResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateThemePreferenceRes {
    return {
      theme: isSet(object.theme) ? Theme.fromJSON(object.theme) : undefined,
      base: isSet(object.base) ? BaseResponse.fromJSON(object.base) : undefined,
    };
  },

  toJSON(message: UpdateThemePreferenceRes): unknown {
    const obj: any = {};
    if (message.theme !== undefined) {
      obj.theme = Theme.toJSON(message.theme);
    }
    if (message.base !== undefined) {
      obj.base = BaseResponse.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateThemePreferenceRes>, I>>(base?: I): UpdateThemePreferenceRes {
    return UpdateThemePreferenceRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateThemePreferenceRes>, I>>(object: I): UpdateThemePreferenceRes {
    const message = createBaseUpdateThemePreferenceRes();
    message.theme = (object.theme !== undefined && object.theme !== null) ? Theme.fromPartial(object.theme) : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseResponse.fromPartial(object.base)
      : undefined;
    return message;
  },
};

/** Service definition */
export interface UserService {
  /** Get current user profile */
  GetProfile(request: GetUserProfileReq): Promise<GetUserProfileRes>;
  /** Update user profile */
  UpdateProfile(request: UpdateUserProfileReq): Promise<UpdateUserProfileRes>;
  /** Update user theme preference */
  UpdateTheme(request: UpdateThemePreferenceReq): Promise<UpdateThemePreferenceRes>;
}

export const UserServiceServiceName = "user.v1.UserService";
export class UserServiceClientImpl implements UserService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || UserServiceServiceName;
    this.rpc = rpc;
    this.GetProfile = this.GetProfile.bind(this);
    this.UpdateProfile = this.UpdateProfile.bind(this);
    this.UpdateTheme = this.UpdateTheme.bind(this);
  }
  GetProfile(request: GetUserProfileReq): Promise<GetUserProfileRes> {
    const data = GetUserProfileReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetProfile", data);
    return promise.then((data) => GetUserProfileRes.decode(new BinaryReader(data)));
  }

  UpdateProfile(request: UpdateUserProfileReq): Promise<UpdateUserProfileRes> {
    const data = UpdateUserProfileReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateProfile", data);
    return promise.then((data) => UpdateUserProfileRes.decode(new BinaryReader(data)));
  }

  UpdateTheme(request: UpdateThemePreferenceReq): Promise<UpdateThemePreferenceRes> {
    const data = UpdateThemePreferenceReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateTheme", data);
    return promise.then((data) => UpdateThemePreferenceRes.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
